### ISSUE TITLE
Description of FROM Instruction Inaccurate

### ISSUE THREAD

**Issue by jamesche75** [docker/docker.github.io#7286] opened 2018-08-29 20:24 UTC
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

The description for the FROM instruction says:
"The FROM instruction initializes a new build stage and sets the Base Image for subsequent instructions."

This is actually not true. The FROM instruction sets the **parent** image. A *base image* in Docker is one that has no parent. Therefore, it's misleading to call the image referred to in the FROM instruction as a base image.

**Comment by e-evdokimov** [comment] 2018-09-21 15:06
The same goes for the description of the FROM instruction in the "Format" section:
"The FROM instruction specifies the Base Image from which you are building. "

**Comment by craig-osterhout** [comment] 2022-05-26 14:46
Thanks for sharing this issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue or a PR in the source repo at https://github.com/docker/cli/tree/master/docs/reference
Closing this issue as unable to fix in this repo.

**Closed by craig-osterhout** 2022-05-26 14:46 UTC
Labels: area/Engine, area/Build
