### ISSUE TITLE
Language-specific guides request

### ISSUE THREAD

**Issue by jcanepa** [docker/docker.github.io#13845] opened 2021-11-15 15:31 UTC
### Problem description

Requesting a language-specific guide for PHP

### Problem location

- I couldn't find the information I wanted. I expected to find it near the following URL: [https://docs.docker.com/language/](https://docs.docker.com/language/)

### Project version(s) affected

None

### Suggestions for a fix

Add a PHP-specific language guide in Docker Docs guides.

**Comment by thaJeztah** [comment] 2021-12-02 14:38
Thanks for requesting; let me close this as duplicate of  https://github.com/docker/docker.github.io/issues/12719

**Closed by thaJeztah** 2021-12-02 14:38 UTC
