### ISSUE TITLE
Base image used in example no longer supports the example.

### ISSUE THREAD

**Issue by moubre** [docker/docker.github.io#13220] opened 2021-07-22 19:29 UTC
File: [get-started/06_bind_mounts.md](https://docs.docker.com/get-started/06_bind_mounts/)

I've repeated this step to ensure that I didn't miss something but the log complains that the module is not compatible and attempts to rebuild it:

yarn install v1.22.5

[1/4] Resolving packages...

[2/4] Fetching packages...

info fsevents@1.2.9: The platform "linux" is incompatible with this module.

info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.

[3/4] Linking dependencies...

error /app/node_modules/sqlite3: Command failed.

Exit code: 1

Command: node-pre-gyp install --fallback-to-build

Arguments:

Directory: /app/node_modules/sqlite3

Output:

**Comment by craig-osterhout** [comment] 2022-05-18 21:07
Thanks for sharing the issue. Closing as duplicate of ##12778

**Closed by craig-osterhout** 2022-05-18 21:07 UTC
