### ISSUE TITLE
Language-specific guides request

### ISSUE THREAD

**Issue by Kurt-von-Laven** [docker/docker.github.io#12771] opened 2021-04-28 19:32 UTC
### Problem description

It would be wonderful to have a guide for UWP (Universal Windows Platform) app development. The associated programming language would be C#. My sense from what I have read so far is that UWP apps can be especially tricky to Dockerize.

### Problem location

I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/language/

### Project version(s) affected

N/A

### Suggestions for a fix

Any Windows-related guide whatsoever would be a great start.

**Comment by thaJeztah** [comment] 2021-12-02 14:27
Thanks for requesting; let me close this one as duplicate of https://github.com/docker/docker.github.io/issues/12697

**Closed by thaJeztah** 2021-12-02 14:27 UTC
