### ISSUE TITLE
"Segmentation fault" when generating the site again after editing a file

### ISSUE THREAD

**Issue by writarium** [docker/docker.github.io#6189] opened 2018-03-10 09:40 UTC
### Problem description
After cloning the repository, the site is successfully generated as shown.

> $ bundle exec jekyll serve
> Configuration file: E:/GIT/docker.github.io/_config.yml
>             Source: E:/GIT/docker.github.io
>        Destination: E:/GIT/docker.github.io/_site
>  Incremental build: enabled
>       Generating...
>                     done in 544.006 seconds.
>  Auto-regeneration: enabled for 'E:/GIT/docker.github.io'
>     Server address: http://127.0.0.1:4000
>   Server running... press ctrl-c to stop.
> 

After this I go my **docker.github.io** folder and make edits to, say the **global-header.html** file. I try to regenerate the site again but the site isn't generated and it stops with the following **Segmentation fault** error. 
I would be grateful if someone could point out what I'm doing wrong here. 

**PS:** Apologies if this is the wrong place but I couldn't find any category related to this error in https://forums.docker.com/ hence posting it here.

> $ bundle exec jekyll serve
> Configuration file: E:/GIT/docker.github.io/_config.yml
>             Source: E:/GIT/docker.github.io
>        Destination: E:/GIT/docker.github.io/_site
>  Incremental build: enabled
>       Generating...
> **Segmentation fault**
>

**Comment by joaofnfernandes** [comment] 2018-03-12 21:23
I'm not really sure what's happening in here. Can you see if this can serve as a workaround?

```
# Clean jekyll files
bundle exec jekyll clean

# Regenerate from scratch
bundle exec jekyll serve
```

**Comment by joaofnfernandes** [comment] 2018-03-13 17:37
Given that both @kolyshkin and I can't reproduce this, I'm closing this issue. @writarium feel free to comment if you're able to find the root cause.

**Closed by joaofnfernandes** 2018-03-13 17:37 UTC
Labels: area/docsite
