### ISSUE TITLE
build number is wrong

### ISSUE THREAD

**Issue by ManoMarks** [docker/docker.github.io#2660] opened 2017-04-07 00:58 UTC
Is there a way to autopopulate the build number?
these 2 lines are out of date:
```
root@a8b2885ab900:/go/src/github.com/docker/docker# cp bundles/1.12.0-dev/binary-client/docker* /usr/bin/
root@a8b2885ab900:/go/src/github.com/docker/docker# cp bundles/1.12.0-dev/binary-daemon/docker* /usr/bin/ 
```

File: [opensource/project/set-up-dev-env.md](https://docs.docker.com/opensource/project/set-up-dev-env/), CC @johndmulhausen

**Comment by johndmulhausen** [comment] 2017-04-07 20:33
We could have a _config.yml variable that had the build number in it and use it here.

**Comment by ManoMarks** [comment] 2017-04-07 21:38
That would work

**Comment by johndmulhausen** [comment] 2017-08-29 22:09
Closing as dupe of #2501

**Closed by johndmulhausen** 2017-08-29 22:09 UTC
Labels: area/docsite, area/opensource
