### ISSUE TITLE
Download link for M1 downloads file with missing .dmg extension.

### ISSUE THREAD

**Issue by GGOUSSEAUD** [docker/docker.github.io#15052] opened 2022-07-05 08:21 UTC
File: [desktop/mac/install.md](https://docs.docker.com/desktop/mac/install/)

**Comment by aroramrinaal** [comment] 2022-07-05 08:31
<img width="1440" alt="Screenshot 2022-07-05 at 2 00 26 PM" src="https://user-images.githubusercontent.com/90490253/177285510-bdb87e4e-5321-4a47-9110-96496a08503f.png">
Works fine for me.

**Comment by kirbysayshi** [comment] 2022-07-07 18:14
This is an issue I ran into too, and was in the process of reporting when I found this GH Issue already. The arm64 vs apple silicon link doesn't matter. It appears to affect Firefox only, as I also tested in Chrome and Safari.

### Expected behavior

- Visit https://docs.docker.com/desktop/mac/install/ using Firefox
- Click "Mac with Intel chip" or "Mac with Apple chip"
- Observe the browser downloading a file named `Docker.dmg`

### Actual behavior

- Visit https://docs.docker.com/desktop/mac/install/
- Click "Mac with Intel chip" or "Mac with Apple chip"
- Observe the browser downloading a file named `Docker` (no extension)
- Once complete, rename the file to `Docker.dmg` and now the image can be mounted by Finder

### Information
  - Browser Version: `Firefox 103.0b5 (64-bit)`

This seems specific to Firefox as the file has the dmg extension when downloaded via Chrome or Safari.

Given the system privileges Docker for Mac has, I was initially very apprehensive about renaming the file and assumed that potentially the servers had been compromised. So while this seems like a minor issue, I don't believe it is since it degrades trust and trains users to not be as cautious.

**Comment by aevesdocker** [comment] 2022-07-11 11:47
Closing PR as this issue has been resolved. The dmg extension is now visible when you download Docker Desktop through Firefox

**Closed by aevesdocker** 2022-07-11 11:47 UTC
