### ISSUE TITLE
Language-specific guides request C#/.NET

### ISSUE THREAD

**Issue by cowhitley** [docker/docker.github.io#14399] opened 2022-03-16 15:09 UTC
Please create a guide for using docker with C#/.NET.

Thank you.

**Comment by geodeasic** [comment] 2022-03-19 17:42
I support this request.

**Comment by thaJeztah** [comment] 2022-04-04 08:05
Thanks for requesting; let me close this as duplicate of https://github.com/docker/docker.github.io/issues/12249

**Closed by thaJeztah** 2022-04-04 08:05 UTC
