### ISSUE TITLE
Language-specific getting started guides for c#/ .net

### ISSUE THREAD

**Issue by zakariabijoy** [docker/docker.github.io#13395] opened 2021-08-23 11:57 UTC
File: [language/index.md](https://docs.docker.com/language/)

**Comment by thaJeztah** [comment] 2021-12-02 14:31
Thanks for requesting; let me close this as duplicate of https://github.com/docker/docker.github.io/issues/12249 and https://github.com/docker/docker.github.io/issues/12697

**Closed by thaJeztah** 2021-12-02 14:31 UTC
