### ISSUE TITLE
3GB of disk space is too low for UCP, 100GB is a good place to start for a production UCP node

### ISSUE THREAD

**Issue by bkauf** [docker/docker.github.io#5420] opened 2017-11-30 19:21 UTC
File: [datacenter/ucp/2.2/guides/admin/install/system-requirements.md](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/install/system-requirements/), CC @jimgalasyn

**Comment by joaofnfernandes** [comment] 2017-11-30 21:16
Closing as duplicate of #3656

**Closed by joaofnfernandes** 2017-11-30 21:16 UTC
Labels: area/ee
