### ISSUE TITLE
Feedback for: engine/getstarted-voting-app/create-swarm.md

### ISSUE THREAD

**Issue by AdHominem** [docker/docker.github.io#1511] opened 2017-02-05 15:35 UTC
File: [engine/getstarted-voting-app/create-swarm.md](https://docs.docker.com/engine/getstarted-voting-app/create-swarm/)

There seems to be a bug regarding the deployment. If you enter all commands and eventually 

`docker@manager:~$ docker stack deploy --compose-file docker-stack.yml vote`

it will eventually output

`Error response from daemon: rpc error: code = 4 desc = context deadline exceeded`

This seems to be a configuration error. The log doesn't seem to be too helpful either:

`docker@manager:~$ cat log.log`
`NEW boot2docker managed disk image (/dev/sda): formatting it for use`

All commands have been entered as suggested (including the docker-stack.yml) so the bug should be replicable easily. 

It should be said that during creation of both machines, it said

Originally I assumed this issue to be related to #1193 but it doesn't seem so.

**Comment by londoncalling** [comment] 2017-02-09 19:50
@ManoMarks @mstanleyjones @friism @johndmulhausen  can you guys take a look at this? I've not gotten this error when I walked through this. Can someone re-produce it?

**Comment by ManoMarks** [comment] 2017-02-09 20:12
Ran through this exactly, I can't replicate this issue. Can you give us more info? Are you running this on Mac? Linux?

On possibility is you're running into resource constraints on the host, I suppose. Do you have a lot of machines running?

Also could be related to [Error response from daemon: rpc error: code = 4 desc = context deadline exceeded ](https://github.com/docker/docker/issues/29087)

**Comment by AdHominem** [comment] 2017-02-10 11:38
I just tried to replicate it again today and it worked. Must have been something environment related. For future reference, I ran this on Linux with no other machines running. Thanks a lot!

**Comment by londoncalling** [comment] 2017-02-10 21:45
@AdHominem thanks, glad it worked for now! 😺

**Comment by nebrass** [comment] 2017-02-11 08:36
@AdHominem I have the same issue as you, with a fresh 1.13 install :(

I tried to reinstall docker, prune system... but nothing work, I have always:
```
example-voting-app (master) docker stack deploy --compose-file docker-stack.yml vote
Creating network vote_backend
Creating network vote_frontend
Creating network vote_default
Creating service vote_vote
```

here is the docker info
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: ch9ui0mvg97rcmhv6gvc0td99
 Is Manager: true
 ClusterID: l1qo1y737o1837azuyhnz0m23
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.8-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: DCF3:USNC:K2NZ:SRI5:F3J5:KVE7:7A4T:YICD:M5QM:AC2E:GWHU:KH43
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 32
 Goroutines: 130
 System Time: 2017-02-11T08:36:00.847915872Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Please help :(

**Comment by londoncalling** [comment] 2017-02-13 20:32
@friism can you all have another look? @ManoMarks  and I could not reproduce this issue, and @AdHominem also reported that everything worked fine on re-install.

**Comment by friism** [comment] 2017-02-13 20:48
This is a swarm-problem that should be reported on `docker/docker`.

**Comment by nebrass** [comment] 2017-02-13 21:16
Bug solved in 
```
Version 1.13.1 (15353)
Channel: Stable
```

**Comment by londoncalling** [comment] 2017-02-14 20:18
@thaJeztah closing this issue (along with the related issue  in [docker/docker/#30988](https://github.com/docker/docker/issues/30988)  ) since it's not reproducible and the folks who originally reported it have since resolved it in their environments.

**Closed by londoncalling** 2017-02-14 20:18 UTC

**Comment by ccamp46** [comment] 2017-02-15 21:36
docker@manager1:~$ docker stack deploy -c vote.yml vote
Updating service vote_visualizer (id: kbj751lbx3gmq0uiqphm2wz54)
Updating service vote_redis (id: tbcw0jkx6e15ie7ndawts9391)
Error response from daemon: rpc error: code = 4 desc = context deadline exceeded
docker@manager1:~$ docker info
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.13.1
