### ISSUE TITLE
Should we add a note on using WSL to get the cURL command?

### ISSUE THREAD

**Issue by raghav710** [docker/docker.github.io#7613] opened 2018-11-05 07:29 UTC
### Problem location

- Other: 
File: [get-started/part3.md](https://docs.docker.com/get-started/part3/)
This file has the following note:
```
Running Windows 10?

Windows 10 PowerShell should already have curl available, but if not you can grab a Linux terminal emulator like Git BASH, or download wget for Windows which is very similar.
```
Should we add a note mentioning that one can also get `curl` and a host of other Linux commands by installing the windows subsystem for Linux? (WSL)

### Suggestions for a fix
We could add a note mentioning that one can also get `curl` and a host of other Linux commands by installing the windows subsystem for Linux? (WSL)

References:
https://docs.microsoft.com/en-us/windows/wsl/install-win10
https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux

**Comment by aevesdocker** [comment] 2022-05-26 14:55
Closing this issue as the information on the referenced page has changed and the issue is no longer relevant.

**Closed by aevesdocker** 2022-05-26 14:55 UTC
