### ISSUE TITLE
I received a 404 when acccessing /docker-for-aws/

### ISSUE THREAD

**Issue by mpanthofer** [docker/docker.github.io#4038] opened 2017-07-31 13:44 UTC
URL: /docker-for-aws/
Full Path: https://docs.docker.com/docker-for-aws/

**Comment by hairyhenderson** [comment] 2017-07-31 15:48
Dupe of #4026, #4027 and #4036 😉

**Comment by mstanleyjones** [comment] 2017-08-18 20:29
This is no longer occurring.

**Closed by mstanleyjones** 2017-08-18 20:29 UTC
