### ISSUE TITLE
install

### ISSUE THREAD

**Issue by MuhamadSatrio** [docker/docker.github.io#12462] opened 2021-03-09 01:31 UTC
File: [docker-for-windows/install.md](https://docs.docker.com/docker-for-windows/install/)
please add windows 10 to install docker

**Comment by craig-osterhout** [comment] 2022-05-02 22:01
Thanks for sharing this issue. As the issue is old, the context may have changed. Closing this issue since Windows 10 is included in the new topic. If the issue persists, please let us know.

**Closed by craig-osterhout** 2022-05-02 22:01 UTC
