### ISSUE TITLE
404 at /registry/spec/api/

### ISSUE THREAD

**Issue by chalianwar** [docker/docker.github.io#3377] opened 2017-05-24 14:05 UTC
URL: /registry/spec/api/

**Comment by jaredestroud** [comment] 2017-06-02 21:22
What page was this URL found on?

**Comment by chalianwar** [comment] 2017-06-02 21:39
Its fixed now: https://docs.docker.com/registry/spec/api/

**Comment by mstanleyjones** [comment] 2017-06-12 23:39
Duplicate of #3375

**Closed by mstanleyjones** 2017-06-12 23:39 UTC
