### ISSUE TITLE
The documentation of `docker run --rm` states incorrectly that it is not compatible with `-d`

### ISSUE THREAD

**Issue by Sebb767** [docker/docker.github.io#6455] opened 2018-04-15 20:13 UTC
The code block in the documentation for `Clean up (--rm)` states:

```
--rm=false: Automatically remove the container when it exits (incompatible with -d)
```

This seems incorrect as it works on my docker installation. The documentation of `-d` also states that it works:

```
If you use -d with --rm, the container is removed when it exits or when the daemon exits, whichever happens first.
```

File: [engine/reference/run.md](https://docs.docker.com/engine/reference/run/), CC @gbarr01

**Comment by gbarr01** [comment] 2018-04-22 15:04
Dupe of #5642 and fixed.

**Closed by gbarr01** 2018-04-22 15:04 UTC
Labels: area/rundoc
