### ISSUE TITLE
Bash completion link for Linux is broken

### ISSUE THREAD

**Issue by lemketron** [docker/docker.github.io#14652] opened 2022-05-03 07:15 UTC
File: [compose/completion.md](https://docs.docker.com/compose/completion/)

Bash completion link for Linux is broken:
https://raw.githubusercontent.com/docker/compose/v2.4.1/contrib/completion/bash/docker-compose

**Comment by craig-osterhout** [comment] 2022-05-06 17:41
Closing. Duplicate of #14617

**Closed by craig-osterhout** 2022-05-06 17:41 UTC
