### ISSUE TITLE
404 at /docker%20-for-%20windows/troubleshoot/

### ISSUE THREAD

**Issue by APIGroupWork** [docker/docker.github.io#12528] opened 2021-03-19 06:39 UTC
I found a broken link : https://docs.docker.com/docker%20-for-%20windows/troubleshoot/#virtualization

**Comment by jerae-duffin** [comment] 2021-05-18 21:34
Hi @APIGroupWork, can you provide more details as to where you found this link?

**Comment by craig-osterhout** [comment] 2022-04-26 21:16
Thanks for sharing the issue. We are unable to reproduce the issue and are closing it due to insufficient information. If you still encounter the issue, please respond with the requested details.

**Closed by craig-osterhout** 2022-04-26 21:16 UTC
