### ISSUE TITLE
Prometheus Monitoring Linux Example seems incorrect

### ISSUE THREAD

**Issue by lanwin** [docker/docker.github.io#5378] opened 2017-11-22 21:17 UTC
File: [engine/admin/prometheus.md](https://docs.docker.com/engine/admin/prometheus/), CC @mistyhacks

Correct me if I am wrong, but I can not get that example running with the given configuration on my Linux Machine.

For me it seems the engine must be bind to "0.0.0.0:9323" and targets: ['172.17.0.1:9323'] to make it work. Otherwise Prometheus can not see the docker target (down).

**Comment by fkaleo** [comment] 2018-01-23 22:08
Probably duplicate of #4972

**Comment by lanwin** [comment] 2018-01-31 10:00
Well at least I have the host option enable.

**Comment by L-Hudson** [comment] 2019-01-02 15:01
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Closed by L-Hudson** 2019-01-02 15:01 UTC
Labels: content/engine
