### ISSUE TITLE
Clarify "reference" in filters for `docker images`

### ISSUE THREAD

**Issue by 0cjs** [docker/docker.github.io#7618] opened 2018-11-06 03:12 UTC
File: [engine/reference/commandline/images.md](https://docs.docker.com/engine/reference/commandline/images/)

There's no clear explanation of how to filter based on repository or tag. We can filter by "reference," which seems to do something similar, but  it doesn't seem to work intuitively: `dr images -f reference=*acme*` will not list images with a repository field of `docker-registry.ec2-1.acme.com:5000/acme/user`. 

The documentation should explain what a "reference" is how it relates to the repository and tag.

**Comment by craig-osterhout** [comment] 2022-05-26 18:25
Thanks for sharing this issue. This particular content is maintained in an upstream repo. Since this issue is dated, I'm not sure if it is still applicable. If the issue is still applicable, please help create an issue or PR in the source repo at https://github.com/docker/cli/tree/master/docs/reference/commandline to get the right people looking at it.
Closing this as unable to fix in this repo.

**Closed by craig-osterhout** 2022-05-26 18:25 UTC
Labels: area/Engine
