### ISSUE TITLE
"Install from binaries" doesn't link to binaries

### ISSUE THREAD

**Issue by broady** [docker/docker.github.io#3947] opened 2017-07-21 17:37 UTC
File: [engine/installation/linux/docker-ce/binaries.md](https://docs.docker.com/engine/installation/linux/docker-ce/binaries/), CC @mstanleyjones

It says:

>  To find the download link, see the release notes for the version of Docker you want to install. You can choose a tar.gz archive or zip archive.

However, the zips in the page linked (moby/moby/releases) don't have binaries, just source.

**Comment by broady** [comment] 2017-07-21 17:44
> Note: those packages won't be updated for the next releases. Get Docker CE from Docker Store

Why? "Docker Store" only points to certain distributions, and for Debian, requires I modify my apt sources. I can't do any of these things, and require a binary distribution.

What's the plan for users like me?

**Comment by mstanleyjones** [comment] 2017-07-24 19:05
Duplicate of #3900

**Closed by mstanleyjones** 2017-07-24 19:05 UTC
