### ISSUE TITLE
Missing section about creating services using templates

### ISSUE THREAD

**Issue by calind** [docker/docker.github.io#2118] opened 2017-03-05 20:00 UTC
The section https://github.com/docker/docker/blob/master/docs/reference/commandline/service_create.md#create-services-using-templates is missing from documentation. 

I couldn't find it neither in https://docs.docker.com/engine/reference/commandline/service_create/ nor https://docs.docker.com/engine/swarm/services/. Actually I wasn't able to find it in the docs.

**Comment by mbentley** [comment] 2017-03-09 18:38
See https://github.com/docker/docker.github.io/issues/1981

**Comment by joaofnfernandes** [comment] 2017-03-16 23:23
I'm closing this as a duplicate of #1981, you can follow any updates there.

**Closed by joaofnfernandes** 2017-03-16 23:23 UTC
