### ISSUE TITLE
This policy is too long.... AWS won't accept it.

### ISSUE THREAD

**Issue by scooter4j** [docker/docker.github.io#5815] opened 2018-01-24 11:25 UTC
File: [docker-for-aws/iam-permissions.md](https://docs.docker.com/docker-for-aws/iam-permissions/), CC @johndmulhausen 

Is there a way to shorten this policy? I'm getting the following error:

Limit exceeded
Your request exceeds one of the limits for this account. Remove one or more existing items and try again. To request a limit increase, contact AWS Customer Support. Learn more
Cannot exceed quota for PolicySize: 6144

**Comment by mistyhacks** [comment] 2018-01-29 17:48
@ddebroy @FrenchBen PTAL

**Comment by FrenchBen** [comment] 2018-01-30 17:13
DUPE of https://github.com/docker/docker.github.io/issues/3939

**Comment by siddharthseetickets** [comment] 2018-04-03 19:01
You can split the policy into multiple files. Each one shouldn't cross 6144 character count.
Solved for me!!!!

**Comment by L-Hudson** [comment] 2019-01-02 17:55
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Closed by L-Hudson** 2019-01-02 17:55 UTC
Labels: area/cloud/aws, area/editions
