### ISSUE TITLE
Cannot search in older documentation (17.03)

### ISSUE THREAD

**Issue by gdevillele** [docker/docker.github.io#4387] opened 2017-08-25 22:26 UTC
File: [index.md](https://docs.docker.com/), CC @johndmulhausen

I don't know how to perform a search in older documentation (17.03 for example).

When I switch to 17.03 and then perform a search, I am back to 17.06 (latest version):

![ezgif-4-83c7fb428c](https://user-images.githubusercontent.com/939999/29734864-97345522-89a9-11e7-9c6c-ca26cc03c23e.gif)

Thank you.

**Comment by johndmulhausen** [comment] 2017-08-28 20:35
We intentionally block the searching of archived documentation by search engines so that the current versions get all the SEO juice. This said, we should think through the UX experience more here (perhaps removing the search) for archived documentation.

**Comment by gdevillele** [comment] 2017-08-28 21:30
Thanks for explaining.

I probably don't know all the details of this problem & context, but here are my two cents:
- removing the search in archived docs would fix this symptom but create a new issue. I am probably not the only one running `17.03` and wanting to search the corresponding documentation, I think search is a basic feature we should offer for all versions.
- If I understand correctly, the issue is the fact that the search implementation has an impact on SEO.

I guess fixing this unwanted search/SEO relation would fix the issue...

I can try to help with this if needed. 🙂

**Comment by johndmulhausen** [comment] 2017-08-29 00:02
I'm thinking we could implement a local search as an offline/fallback kind of thing. For example right now we populate /metadata.txt -- we could also generate /content.txt. The full contents of such a file in source would simply be:

```
---
layout: null
---
{{ site.pages | jsonify }}
```

This produces a JSON blob of the entire docs content that could be pulled in to JS and wired to keyboard input so people could search the docs. Use AJAX/`setTimeout` so that people get a spinning wheel and you're off to the races. The ranking wouldn't be as good but it would be something.

**Comment by gdevillele** [comment] 2017-08-30 17:03
Thanks.

I think a local search is a good way of solving the problem. 👍

I am not sure I understand the implementation proposal, would the entire content of the docs be downloaded by the web browser, or would the browser send asynchronous requests to the server to retrieve search results?

**Comment by johndmulhausen** [comment] 2017-10-27 22:13
Closing this as by design we have decided not to implement search functionality for older docs which are for reference only. To this end we have disabled the search bar entirely. Local search proved to be too problematic; we don't have a server-side index to offer and would basically rely on users downloading a json blob of the entire docset text when running search, which would be tens of MB in size.

**Closed by johndmulhausen** 2017-10-27 22:13 UTC
Labels: area/docsite
