### ISSUE TITLE
Section anchor links opened from an external source does not scroll properly

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker.github.io#2199] opened 2017-03-08 20:42 UTC
### Problem description

If you open a `#section` link in the Dockerfile reference page from an external page, the page doesn't scroll properly. Clicking the section links when you're already on the page is fine though.

### Problem location

1. Open this link: https://docs.docker.com/engine/reference/builder/#arg
2. Notice that you ultimately end up in: https://docs.docker.com/engine/reference/builder/#user
`ARG` isn't even visible here.
3. Open this link: https://docs.docker.com/engine/reference/builder/#env
4. Notice that you ultimately end up in: https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
But at least you can see `ENV` at the bottom.

Zooming in your browser (via Ctrl++ or whatever) will make the problem even more noticeable as it pushes even more content further down the page.

**Comment by dsheets** [comment] 2017-04-21 15:20
This seems to be mostly fixed but in FF 52 on OS X 10.11.6 it still happens when you change the anchor in the URL bar and hit enter. It works on page load and on navigation bar clicking but not on in-page manual navigation. It may also be using JavaScript so I'm not sure how degraded the experience is for NoScript users or if we care about them (requiring JS to read docs seems a bit OTT but maybe there is a policy).

**Comment by johndmulhausen** [comment] 2017-08-28 23:55
Can repro in Firefox. Chrome and Safari are fine.

**Comment by mistyhacks** [comment] 2018-02-02 23:29
@jsouth care to take a crack?

**Comment by jsouth** [comment] 2018-02-08 00:09
@mistyhacks - Apologies for delayed response. For sure, i'll see if I can remedy this. :)

**Comment by joaofnfernandes** [comment] 2018-04-02 17:20
I can reproduce @dsheets experience with:
* FF 59
* FF nightly
* Chrome latest

**Comment by L-Hudson** [comment] 2018-12-04 16:18
Cannot reproduce issue; fixed in recent build. Closing ticket.

**Closed by L-Hudson** 2018-12-04 16:18 UTC
Labels: area/site
