### ISSUE TITLE
htpasswd not part of the default packages

### ISSUE THREAD

**Issue by fabricev** [docker/docker.github.io#11790] opened 2020-11-23 14:01 UTC
File: [registry/deploying.md](https://docs.docker.com/registry/deploying/)

There are other Docker alternatives like
https://hub.docker.com/r/xmartlabs/htpasswd/dockerfile

**Comment by craig-osterhout** [comment] 2022-06-16 21:46
This looks like a duplicate of https://github.com/docker/docker.github.io/issues/11908
Fixed in https://github.com/docker/docker.github.io/commit/d39b0d8e6e047ffcf5d0e6eecf45b3495437ceb8

**Closed by craig-osterhout** 2022-06-16 21:46 UTC
