### ISSUE TITLE
Windows CMD did not accept $(pwd)

### ISSUE THREAD

**Issue by Jack-R-Long** [docker/docker.github.io#12662] opened 2021-04-12 21:08 UTC
File: [get-started/06_bind_mounts.md](https://docs.docker.com/get-started/06_bind_mounts/)

Had to replace the `$(pwd)` with the CMD equivalent `%cd%` in the following command:
`docker run -dp 3000:3000 -w /app -v "$(pwd):/app" node:12-alpine sh -c "yarn install && yarn run dev"`

See error below:
docker: Error response from daemon: create $(pwd): "$(pwd)" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'

**Comment by craig-osterhout** [comment] 2022-05-02 21:35
Thanks for sharing this issue. The example command is for PowerShell, not CMD. Closing this issue as PowerShell is specified in the documentation. If the issue still persists, please let us know.

**Closed by craig-osterhout** 2022-05-02 21:35 UTC

**Comment by craig-osterhout** [comment] 2022-05-11 18:12
Duplicate of  #14686
