### ISSUE TITLE
404 at /Install/linux/docker-ce/centos/

### ISSUE THREAD

**Issue by rggkkzzz** [docker/docker.github.io#12459] opened 2021-03-08 13:05 UTC
I found a broken link : https://docs.docker.com/Install/linux/docker-ce/centos/

**Comment by jerae-duffin** [comment] 2021-05-20 19:15
Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

**Comment by thaJeztah** [comment] 2021-05-20 20:24
I was confused for a bit, because we have a redirect for that URL; https://github.com/docker/docker.github.io/blame/2a84b757394cb9a2b03f8b4e9f306669885feb5c/engine/install/centos.md#L6

But then I noticed that the "broken" URL is starting with a capital `I`, so looks like a typo somewhere.


@rggkkzzz the correct URL you're looking for is; https://docs.docker.com/engine/install/centos/

**Comment by craig-osterhout** [comment] 2022-04-26 21:17
Thanks for sharing the issue. We are unable to reproduce the issue and are closing it due to insufficient information. If you still encounter the issue, please respond with the requested details.

**Closed by craig-osterhout** 2022-04-26 21:17 UTC
