### ISSUE TITLE
Installation not working on Ubuntu 19.10

### ISSUE THREAD

**Issue by mcamou** [docker/docker.github.io#8891] opened 2019-06-04 07:18 UTC
File: [install/linux/docker-ce/ubuntu.md](https://docs.docker.com/install/linux/docker-ce/ubuntu/)

I've tried to install Docker on Ubuntu 19.04. I followed the directions, but I get the following errors:

```
# apt-get install docker-ce docker-ce-cli containerd.io
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'docker-ce' has no installation candidate
E: Unable to locate package docker-ce-cli
```

`apt update` works correctly:
```
# apt update                                                                                
...
Hit:12 https://download.docker.com/linux/ubuntu disco InRelease
...
Fetched 74.6 kB in 4s (21.2 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
```

**Comment by thaJeztah** [comment] 2019-06-04 13:36
Ubuntu 19.04 is not yet in the list of supported distros for Docker 18.09, but will be coming with Docker 19.03 (beta/release-candidates are available in the "test" channel)

<img width="645" alt="Screenshot 2019-06-04 at 15 34 53" src="https://user-images.githubusercontent.com/1804568/58883308-69f47180-86de-11e9-90fc-16faa846abdb.png">


Closing this issue because of the above, but feel free to continue the conversation

**Closed by thaJeztah** 2019-06-04 13:36 UTC

**Comment by ruurtjan** [comment] 2019-10-17 20:26
@thaJeztah Docker 19.03 has been released, but the installation instructions still yields an error:
```
 sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

Hit:1 http://security.ubuntu.com/ubuntu eoan-security InRelease
Hit:2 http://fr.archive.ubuntu.com/ubuntu eoan InRelease                  
Hit:3 http://fr.archive.ubuntu.com/ubuntu eoan-updates InRelease          
Hit:4 http://fr.archive.ubuntu.com/ubuntu eoan-backports InRelease
Ign:5 https://download.docker.com/linux/ubuntu eoan InRelease
Err:6 https://download.docker.com/linux/ubuntu eoan Release
  404  Not Found [IP: 99.86.115.96 443]
Reading package lists... Done
E: The repository 'https://download.docker.com/linux/ubuntu eoan Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Is there a workaround, or can we expect it to land soon?

**Comment by thaJeztah** [comment] 2019-10-18 16:54
@ruurtjan the original issue reported above was on Ubuntu 19.04 (although I see the title said "19.10"). Packages are available for ubuntu 19.04 "disco" now, but 19.10 not yet; I think it was released Yesterday; most likely will come with the next Docker release (but that's still some time out).

In the meantime you can try installing the package for Ubuntu 19.04 on Ubuntu 19.10 (which likely will work, but not tested), and I'll have a look if it can be added to the nightly builds.

**Comment by hack2root** [comment] 2019-10-19 12:34
You can install 19.04 and then docker, then update to 19.10

> Is there a workaround, or can we expect it to land soon?

**Comment by ruurtjan** [comment] 2019-10-19 20:14
> In the meantime you can try installing the package for Ubuntu 19.04 on Ubuntu 19.10 (which likely will work, but not tested), and I'll have a look if it can be added to the nightly builds.

Jep, got `hello-world` running correctly on Ubuntu 19.10 (`eoan`) with the `disco` repo using:
```
 sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   disco \
   stable"
```
Thanks!

**Comment by postables** [comment] 2019-10-26 23:47
> > In the meantime you can try installing the package for Ubuntu 19.04 on Ubuntu 19.10 (which likely will work, but not tested), and I'll have a look if it can be added to the nightly builds.
> 
> Jep, got `hello-world` running correctly on Ubuntu 19.10 (`eoan`) with the `disco` repo using:
> 
> ```
>  sudo add-apt-repository \
>    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
>    disco \
>    stable"
> ```
> 
> Thanks!

This worked for me, thanks

**Comment by rivajunior** [comment] 2019-10-31 13:48
> > In the meantime you can try installing the package for Ubuntu 19.04 on Ubuntu 19.10 (which likely will work, but not tested), and I'll have a look if it can be added to the nightly builds.
> 
> Jep, got `hello-world` running correctly on Ubuntu 19.10 (`eoan`) with the `disco` repo using:
> 
> ```
>  sudo add-apt-repository \
>    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
>    disco \
>    stable"
> ```
> 
> Thanks!

Did not worked for me.

I've got the following
```terminal
$ ~ sudo apt-get update
Get:1 http://br.archive.ubuntu.com/ubuntu eoan InRelease [255 kB]
Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease                                                                                                        
Hit:3 http://ppa.launchpad.net/git-core/ppa/ubuntu eoan InRelease                                                                                                   
Hit:4 http://dl.google.com/linux/chrome/deb stable Release                                                                                                          
Get:5 https://download.docker.com/linux/ubuntu disco InRelease [44,4 kB]                                                         
Hit:6 http://security.ubuntu.com/ubuntu eoan-security InRelease                       
Err:5 https://download.docker.com/linux/ubuntu disco InRelease                        
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
Get:8 http://br.archive.ubuntu.com/ubuntu eoan-updates InRelease [88,4 kB]
Get:9 http://br.archive.ubuntu.com/ubuntu eoan-backports InRelease [79,7 kB]
Get:10 http://br.archive.ubuntu.com/ubuntu eoan-updates/main amd64 DEP-11 Metadata [208 B]
Reading package lists... Done            
W: GPG error: https://download.docker.com/linux/ubuntu disco InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
E: The repository 'https://download.docker.com/linux/ubuntu disco InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by thaJeztah** [comment] 2019-10-31 14:52
@rivajunior I'm not able to reproduce that problem; perhaps you missed a step in the installation steps (https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-repository) ?

```bash
sudo apt-get update

sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
```

check the key

```bash
sudo apt-key fingerprint 0EBFCD88

pub   rsa4096 2017-02-22 [SCEA]
      9DC8 5822 9FC7 DD38 854A  E2D8 8D81 803C 0EBF CD88
uid           [ unknown] Docker Release (CE deb) <docker@docker.com>
sub   rsa4096 2017-02-22 [S]
```

Add the "disco" repository, and install docker

```bash
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   disco \
   stable"

sudo apt-get install docker-ce docker-ce-cli containerd.io
```

Verify the install

```bash
sudo docker version

Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 01:00:44 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2f86
  Built:            Tue Oct  8 00:59:17 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by rivajunior** [comment] 2019-11-04 12:20
> @rivajunior I'm not able to reproduce that problem; perhaps you missed a step in the installation steps (https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-repository) ?
> 
> ```shell
> sudo apt-get update
> 
> sudo apt-get install \
>     apt-transport-https \
>     ca-certificates \
>     curl \
>     gnupg-agent \
>     software-properties-common
> 
> curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
> ```
> 
> check the key
> 
> ```shell
> sudo apt-key fingerprint 0EBFCD88
> 
> pub   rsa4096 2017-02-22 [SCEA]
>       9DC8 5822 9FC7 DD38 854A  E2D8 8D81 803C 0EBF CD88
> uid           [ unknown] Docker Release (CE deb) <docker@docker.com>
> sub   rsa4096 2017-02-22 [S]
> ```
> 
> Add the "disco" repository, and install docker
> 
> ```shell
> sudo add-apt-repository \
>    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
>    disco \
>    stable"
> 
> sudo apt-get install docker-ce docker-ce-cli containerd.io
> ```
> 
> Verify the install
> 
> ```shell
> sudo docker version
> 
> Client: Docker Engine - Community
>  Version:           19.03.3
>  API version:       1.40
>  Go version:        go1.12.10
>  Git commit:        a872fc2f86
>  Built:             Tue Oct  8 01:00:44 2019
>  OS/Arch:           linux/amd64
>  Experimental:      false
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          19.03.3
>   API version:      1.40 (minimum version 1.12)
>   Go version:       go1.12.10
>   Git commit:       a872fc2f86
>   Built:            Tue Oct  8 00:59:17 2019
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.2.10
>   GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
>  runc:
>   Version:          1.0.0-rc8+dev
>   GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
>  docker-init:
>   Version:          0.18.0
>   GitCommit:        fec3683
> ```

Yes! I really missed a step on the installation steps. Thanks for your help!

**Comment by eclectic-coding** [comment] 2019-11-20 14:04
@rivajunior 
Thank you I was able to finally install Docker-CE on Ubuntu / POP_OS 19.10.

**Comment by pdigit101** [comment] 2019-11-27 16:14
@rivajunior
Worked for me as well on my Ubuntu 19.10, Thank you!

**Comment by ozkanaltuner** [comment] 2019-12-02 09:29
This issue should remain open. Problem still persists.

**Comment by manikantanekkalapudi** [comment] 2019-12-14 16:34
This worked for me!

**Comment by zilexa** [comment] 2019-12-22 01:43
Unfortunately, I followed the exact steps on Ubuntu Budgie 19.10 and keep getting the same error. Completely removed Docker and tried again 3 times. Same result:

```
Setting up docker-ce-cli (5:19.03.3~3-0~ubuntu-disco) ...
Setting up docker-ce (5:19.03.3~3-0~ubuntu-disco) ...
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2019-12-22 02:42:21 CET; 3ms ago
     Docs: https://docs.docker.com
  Process: 5172 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
 Main PID: 5172 (code=exited, status=1/FAILURE)
dpkg: error processing package docker-ce (--configure):
 installed docker-ce package post-installation script subprocess returned error exit status 1
Processing triggers for man-db (2.8.7-3) ...
Processing triggers for systemd (242-7ubuntu3.2) ...
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by rallen71366** [comment] 2019-12-22 03:04
I managed to get the latest release of Docker running on my Kubuntu 19.10 install just by going to snapcraft.io and installing the snap. That easy.

**Comment by zilexa** [comment] 2019-12-22 16:04
> I managed to get the latest release of Docker running on my Kubuntu 19.10 install just by going to snapcraft.io and installing the snap. That easy.

Easy but performance will suffer. Snap packages start up a bit slower. [Source](https://arstechnica.com/gadgets/2019/11/ubuntu-19-10-quite-simply-the-best-ubuntu-canonical-has-ever-released/) (page 2 with Chromium browser as an example). 

There should be a way to install the right version that works on 19.10..

**Comment by zilexa** [comment] 2019-12-28 15:25
I tried installing via Snap, also does not work!
```
$ sudo snap install docker
error: cannot perform the following tasks:
- Setup snap "docker" (423) security profiles (cannot setup apparmor for snap "docker": cannot load apparmor profiles: exit status 1
apparmor_parser output:
Cache read/write disabled: interface file missing. (Kernel needs AppArmor 2.4 compatibility patch.)
Warning: unable to find a suitable fs in /proc/mounts, is it mounted?
Use --subdomainfs to override.
)
- Setup snap "docker" (423) security profiles (cannot load apparmor profiles: exit status 1
apparmor_parser output:
Cache read/write disabled: interface file missing. (Kernel needs AppArmor 2.4 compatibility patch.)
Warning: unable to find a suitable fs in /proc/mounts, is it mounted?
Use --subdomainfs to override.
)
```

**Comment by abr4xas** [comment] 2020-02-10 13:47
I'm having problems to install Docker on Ubunbtu 19.10

```bash
# Executing docker install script, commit: f45d7c11389849ff46a6b4d94e0dd1ffebca32c1
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sh -c echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu eoan stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
+ [ -n  ]
+ sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
E: Package 'docker-ce' has no installation candidate
```

I'm using this script:

```bash
#!/bin/bash

if [[ $USER != root ]]; then
    echo "############################################"
    echo "#  ROOT ###"
    echo "##########################################"
    exit 1
fi

set -eu
export DEBIAN_FRONTEND=noninteractive

#
command -v docker >/dev/null 2>&1 || {
    echo >&2 "Docker..."
    apt-get update --fix-missing
    curl -sSL https://get.docker.com/ | sh
    sleep 4.0
    echo >&2 "Done..."
}

#
command -v docker-compose >/dev/null 2>&1 || {
    echo >&2 "docker-compose"
    COMPOSE_VERSION=$1
    curl -L https://github.com/docker/compose/releases/download/$COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
    sleep 4.0
    echo >&2 "Done..."
}

sudo usermod -aG docker ${USER}

exit 0;
```

`sudo ./docker-config.sh 1.25.4`

**Comment by rationalthinker1** [comment] 2020-02-15 20:39
As for me, I had to download containerd.io from https://ubuntu.pkgs.org/19.10/docker-ce-test-amd64/containerd.io_1.2.11-2_amd64.deb.html to get it to work.

**Comment by TriMoon** [comment] 2020-02-25 11:42
I am unable to install also on 19.10, please see https://github.com/docker/docker.github.io/issues/10347#issuecomment-590824332 :disappointed:

**Comment by chris-crone** [comment] 2020-03-20 13:37
Hi @TriMoon! There should now be Ubuntu 19.10 packages up. Do you still have this problem?

**Comment by TriMoon** [comment] 2020-03-22 08:50
@chris-crone ill try again later and update this reply. (Currently busy with other important stuff)

**Comment by 2absolutes** [comment] 2020-04-08 02:03
Hi @chris-crone, Still facing this problem.

sudo apt remove docker-ce docker-ce-cli containerd.io
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'containerd.io' is not installed, so not removed
Package 'docker-ce-cli' is not installed, so not removed
Package 'docker-ce' is not installed, so not removed
The following packages were automatically installed and are no longer required:
  aufs-tools cgroupfs-mount pigz
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
piyushchoudhary@piyush-pc:~$ sudo apt-get install docker-ce docker-ce-cli containerd.io
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  containerd.io docker-ce docker-ce-cli
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/85.6 MB of archives.
After this operation, 384 MB of additional disk space will be used.
Selecting previously unselected package containerd.io.
(Reading database ... 263084 files and directories currently installed.)
Preparing to unpack .../containerd.io_1.2.13-1_amd64.deb ...
Unpacking containerd.io (1.2.13-1) ...
Selecting previously unselected package docker-ce-cli.
Preparing to unpack .../docker-ce-cli_5%3a19.03.8~3-0~ubuntu-eoan_amd64.deb ...
Unpacking docker-ce-cli (5:19.03.8~3-0~ubuntu-eoan) ...
Selecting previously unselected package docker-ce.
Preparing to unpack .../docker-ce_5%3a19.03.8~3-0~ubuntu-eoan_amd64.deb ...
Unpacking docker-ce (5:19.03.8~3-0~ubuntu-eoan) ...
Setting up containerd.io (1.2.13-1) ...
Setting up docker-ce-cli (5:19.03.8~3-0~ubuntu-eoan) ...
Setting up docker-ce (5:19.03.8~3-0~ubuntu-eoan) ...
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2020-04-07 22:01:31 EDT; 8ms ago
     Docs: https://docs.docker.com
  Process: 15790 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
 Main PID: 15790 (code=exited, status=1/FAILURE)
dpkg: error processing package docker-ce (--configure):
 installed docker-ce package post-installation script subprocess returned error exit status 1
Processing triggers for man-db (2.8.7-3) ...
Processing triggers for systemd (242-7ubuntu3.2pop1~1575565723~19.10~6a5852b) ...
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by 2absolutes** [comment] 2020-04-08 02:32
Nvm got it working. Seems like I had not installed some new os updates. After getting those, rebooting and reinstalling, it installed without any hiccups

**Comment by DmytroRybka** [comment] 2020-04-13 18:55
Worked for me with 
`sudo snap install docker`

**Comment by thaJeztah** [comment] 2020-04-14 15:58
The `snap` packages won't install the official packages, and I've seen some issues reported when running those, so I would not currently recommend running those.

Packages for ubuntu 19.10 should be available now on download.docker.com, so installation should work. Note though that 19.10 is not an LTS release, so once 19.10 reaches EOL, no new packages will be published.
