### ISSUE TITLE
docker run hello-world

### ISSUE THREAD

**Issue by sudipto84goswami** [docker/docker.github.io#2425] opened 2017-03-21 19:28 UTC
Hi Team,

I am unable to run any docker container. The host on which installation is done in running on CentOS7 and is behind internet. I though have a proxy setting enabled on this host which is working fine.

Command: docker run hello-world
Unable to find image 'hello-world:latest' locally
Trying to pull repository registry.access.redhat.com/hello-world ... not found
latest: Pulling from docker.io/hello-world

50a54e1f9180: Pulling fs layer
7a5a2d73abce: Pulling fs layer
Trying to pull repository docker.io/hello-world ... failed
FATA[0006] Could not reach any registry endpoint

Docker Version:
Client version: 1.5.0-dev
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): fc0329b/1.5.0
OS/Arch (client): linux/amd64
Server version: 1.5.0-dev
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): fc0329b/1.5.0
OS/Arch (server): linux/amd64

Docker Info:
Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-253:3-8456823-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 307.2 MB
 Data Space Total: 107.4 GB
 Data Space Available: 3.519 GB
 Metadata Space Used: 733.2 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.20.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 31.26 GiB
Name: <hostname>
ID: <code>

Can you please help me on this. In addition just curious to know, can i create container locally and host some application on top of it like Jupyter/R etc and let the other users access it. And for doing this, is internet a mandate thing. i.e. will the server needs internet connection to run the docker commands.

It will be really helpful if some one looks into this and helps me on solving this.

**Comment by thaJeztah** [comment] 2017-03-21 20:28
this is expected; docker 1.5 does not support the V2 registry protocol, and V1 registry support ended in 2015, see https://blog.docker.com/2015/10/docker-hub-deprecation-1-5/

I really recommend updating to a more recent version of a Docker, because version 1.5 is EOL for a long time, and really insecure (as are images pulled from V1 registries)

I'll close this issue, because this is not a bug, and also not related to the documentation

**Closed by thaJeztah** 2017-03-21 20:28 UTC

**Comment by sudipto84goswami** [comment] 2017-03-21 23:54
I am unable to download the RPM from  https://download.docker.com/linux/centos/7/x86_64/stable/Packages/  which is mentioned in Docker page. It seems the page is not opening. Can you please check that.

Also I am running on CentOS 7.1 , so is this OS version compatible with Docker - CE.

Please confirm.

**Comment by thaJeztah** [comment] 2017-03-22 10:40
Oh, looks like the instructions for offline installation assume the index pages are there, but they are currently missing, see https://github.com/docker/docker/issues/31987

You can download the packages using these URLs;

https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-17.03.0.ce-1.el7.centos.x86_64.rpm
https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-selinux-17.03.0.ce-1.el7.centos.noarch.rpm

> Also I am running on CentOS 7.1 , so is this OS version compatible with Docker - CE

CentOS is a rolling release, so generally we would only be able to support the current
version of CentOS (which is 7.3). The CentOS package repositories for older version than
7.3 are no longer available, so installing on those versions of the distro may result
in issues when installing dependencies. There are some breaking changes in recent
CentOS patch releases, causing SELinux policies to fail, so you'll have to test if it
works if you have SELinux enabled.

If needed, older versions of docker (still named `docker-engine`) can be found
in the old repository; http://yum.dockerproject.org/repo/main/centos/7/Packages/


> In addition, can we create containers locally and this does not require any internet connection on the host.

You can create containers without internet connection, either by running a local registry
that contains the images you want to use, by building your own base images "from scratch" (which is a bit more involved),
or by downloading the images you need on a docker installation that _has_ internet access,
and `docker save` those images to a file, transfer those files to the machine that doesn't have internet access,
and `docker load` the images there.

When building images (`docker build`), chances are you'll need internet access though,
so doing that may require you to build those images on a machine with internet access, then 
transfer them (as described above).
