### ISSUE TITLE
main vs. master branch

### ISSUE THREAD

**Issue by meni181818** [docker/docker.github.io#15141] opened 2022-07-18 09:20 UTC
### Problem location

- I saw a problem at the following URL: https://docs.docker.com/language/python/configure-ci-cd/

- the workflow and the description mentioning a **main** branch while the actual project uses **master** branch instead, as shown in the picturs as well.

### Suggestions for a fix

- replace main with master.

**Comment by craig-osterhout** [comment] 2022-08-02 22:36
Duplicate of #13159, although different language guide.

**Closed** 2022-08-23 20:43 UTC
Labels: area/configuration
