### ISSUE TITLE
broken links at bottom

### ISSUE THREAD

**Issue by zero-zero0** [docker/docker.github.io#10355] opened 2020-02-26 03:23 UTC
links at bottom of page [0] are broken and need to be updated in the section copied below.

Next steps
    Continue to Post-installation steps for Linux [1]
    Continue with the User Guide. [2]

[0] https://docs.docker.com/install/linux/docker-ce/ubuntu/

[1] https://docs.docker.com/install/linux/linux-postinstall.md
[2] https://docs.docker.com/get-started/index.md

File: [install/linux/docker-ce/ubuntu.md](https://docs.docker.com/install/linux/docker-ce/ubuntu/)

**Comment by usha-mandya** [comment] 2020-02-26 09:58
@zero-zero0 -  Thank you for the feedback. The links in https://docs.docker.com/install/linux/docker-ce/ubuntu/#next-steps work fine for me. Not sure why they appear broken for you. I'm closing this issue as I cannot reproduce it. If the issue still persists, please reopen it with more information.

**Closed by usha-mandya** 2020-02-26 09:58 UTC
