### ISSUE TITLE
"Edit this page" link gives 404

### ISSUE THREAD

**Issue by cowlinator** [docker/docker.github.io#6316] opened 2018-03-26 21:42 UTC
### Problem description

The "edit this page" link is broken on https://docs.docker.com/engine/reference/builder/
The link is to https://github.com/docker/docker.github.io/edit/master/engine/reference/builder.md , but no builder.md file exists in that reference directory

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/reference/builder/

### Suggestions for a fix

Link to the appropriate file

**Comment by joaofnfernandes** [comment] 2018-03-26 23:24
Some docs are managed in upstream repositories. That particular doc is managed at [docker/cli](https://github.com/docker/cli/blob/master/docs/reference/builder.md).

Feel free to open your pull request against that repository.
I'm going to close this issue as a duplicate of #6102

**Closed by joaofnfernandes** 2018-03-26 23:24 UTC
