### ISSUE TITLE
Language-specific guides request - PHP

### ISSUE THREAD

**Issue by mohangade08** [docker/docker.github.io#14074] opened 2022-01-07 11:06 UTC
### Problem location

- I saw a problem at the following URL: <Add URL>

- I couldn't find the information I wanted. I expected to find it near the following URL <Add the URL and briefly describe how we can improve the existing content>

- Other: <Add details that can help us understand the issue>

**Comment by tymik** [comment] 2022-01-19 22:05
Thank you for you report. I am closing it as a duplicate of #12719

**Closed by tymik** 2022-01-19 22:05 UTC
