### ISSUE TITLE
404 at /engine/installation/linux/docker-ce/linux-postinstall/

### ISSUE THREAD

**Issue by vmmqa** [docker/docker.github.io#4058] opened 2017-08-01 01:14 UTC
URL: /engine/installation/linux/docker-ce/linux-postinstall/
the link is lost

**Comment by maartenligtvoet** [comment] 2017-08-02 13:56
Is this the same issue as? https://github.com/docker/docker.github.io/issues/4061

**Comment by mstanleyjones** [comment] 2017-08-18 20:23
Duplicate of #4061

**Closed by mstanleyjones** 2017-08-18 20:23 UTC
