### ISSUE TITLE
This is a wrong and duplicated tutorial for communicate between a container and a swarm service

### ISSUE THREAD

**Issue by jakieNguyen** [docker/docker.github.io#9046] opened 2019-07-11 10:42 UTC
File: [network/network-tutorial-overlay.md](https://docs.docker.com/network/network-tutorial-overlay/)
At link https://docs.docker.com/network/network-tutorial-overlay/#communicate-between-a-container-and-a-swarm-service
The tutorial is nothing related to overlay network but just a duplicate of a bridge network tutorial
https://docs.docker.com/network/network-tutorial-standalone/

**Comment by pluckhuang** [comment] 2019-09-26 13:26
Duplicate of # +1,
 i also found that "Communicate between a container and a swarm service" this doc was the same as "Use the default bridge network".

**Comment by craig-osterhout** [comment] 2022-08-18 20:21
Thanks for sharing the issue. Closing as duplicate of https://github.com/docker/docker.github.io/issues/8387

**Closed by craig-osterhout** 2022-08-18 20:21 UTC
Labels: area/Networking
