### ISSUE TITLE
something is wrong with the format (last section)

### ISSUE THREAD

**Issue by kiddo3** [docker/docker.github.io#5752] opened 2018-01-16 11:26 UTC
File: [engine/reference/commandline/service_create.md](https://docs.docker.com/engine/reference/commandline/service_create/), CC @mistyhacks

**Comment by joaofnfernandes** [comment] 2018-01-16 18:23
Thanks for reporting this @kiddo3! I'm closing it as a duplicate of #5725.
/cc @mistyhacks and @johndmulhausen for visibility.

**Closed by joaofnfernandes** 2018-01-16 18:23 UTC
