### ISSUE TITLE
Can't apk add python from 12-alpine, as shown in the text to create the /app dockerfile with

### ISSUE THREAD

**Issue by stevelatta** [docker/docker.github.io#13798] opened 2021-11-05 21:17 UTC
File: [get-started/02_our_app.md](https://docs.docker.com/get-started/02_our_app/) 

Using Windows 11, using VScode + terminal for this tutorial
 Downloaded the entire tutorial, and went to the /app folder, created the Dockerfile and added the suggested text, but apk add is failing on python.  

 > [2/5] RUN apk add --no-cache python g++ make:
#9 0.396 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
#9 0.664 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
#9 1.018 ERROR: unable to select packages:
#9 1.045   python (no such package):
#9 1.045     required by: world[python]

**Comment by thaJeztah** [comment] 2021-11-12 17:08
Thanks for reporting; I think this should be fixed by https://github.com/docker/docker.github.io/pull/13826, which is now published on docs.docker.com.

Let me go ahead and close this ticket, but feel free to continue the conversation if the issue is not resolved 👍

**Closed by thaJeztah** 2021-11-12 17:08 UTC
