### ISSUE TITLE
Development 'Get Started' page not found

### ISSUE THREAD

**Issue by BrianMiller793** [docker/docker.github.io#10554] opened 2020-04-01 16:13 UTC
### Problem description

Page 'https://docs.docker.com/develop/', Prerequisites section, "Get started" link leads to 404.

### Problem location
404 error:
https://docs.docker.com/get-started/index.md

**Comment by usha-mandya** [comment] 2020-04-03 10:22
Hello @BrianMiller793, the link to the Get started page from https://docs.docker.com/develop/ works fine for me. Could you try again?
I'm closing this issue as I could not reproduce the issue. Please feel free to reopen if you are still experiencing the issue. Thanks.

**Closed by usha-mandya** 2020-04-03 10:22 UTC
