### ISSUE TITLE
Broken link - Docker examples not opening up in "engine reference" docs

### ISSUE THREAD

**Issue by jyotendra** [docker/docker.github.io#8056] opened 2019-01-21 08:49 UTC
### Problem description

Clicking on this [link](https://docs.docker.com/engine/reference/#dockerfile-examples) from docker referennce [here](https://docs.docker.com/engine/reference/builder) shows up "we can't find the page".

It should have shown dockerFile examples.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/reference/#dockerfile-examples

**Comment by thaJeztah** [comment] 2019-02-11 15:23
Looks like the issue is that there's a base href set on that page;

<img width="769" alt="screenshot 2019-02-11 at 16 22 07" src="https://user-images.githubusercontent.com/1804568/52572968-59f80f80-2e19-11e9-84ec-b92c84ce961f.png">

**Comment by thaJeztah** [comment] 2019-02-11 15:25
Probably created in this template; https://github.com/docker/docker.github.io/blob/master/_layouts/docs.html#L38

**Comment by ahh-docker** [comment] 2019-02-11 15:30
@L-Hudson according to @thaJeztah, we should be very careful on any changes to this file, please advise on how to move forward with this.

It looks like it's creating a URL that works if you click inside the page, but if you copy it via the browser, the URL ends up leaving off "builder". The user gets https://docs.docker.com/engine/reference/#dockerfile-examples instead of https://docs.docker.com/engine/reference/builder/#dockerfile-examples.

@thaJeztah says it's related to the template, and it might be related to other reference pages as well.

**Comment by paigehargrave** [comment] 2019-02-26 12:45
@jyotendra @thaJeztah Thank you for bringing this up and for your time here! It looks like this has been fixed and the link is going to https://docs.docker.com/engine/examples/.  I'm going to go ahead and close this issue. Please reopen if there is still a concern.

**Closed by paigehargrave** 2019-02-26 12:45 UTC
Labels: content/404, content/engine
