### ISSUE TITLE
Feedback on Get Started with Docker for Windows

### ISSUE THREAD

**Issue by JimGalasyn** [docker/docker.github.io#3078] opened 2017-04-26 16:17 UTC
Here's a brain dump from my review, done on a Windows 10 Enterprise box. Most of the feedback is actually about the Docker Cloud topics. Overall, I wasn't entirely successful, but I got 95% of the way there.

[Part 4](https://docs.docker.com/get-started/part4/#deploy-your-app-on-a-cluster):
In PowerShell, `docker-machine scp` fails:
```ps
PS C:\Users\Jim\Documents\get-started> docker-machine scp docker-compose.yml myvm1:~
You must have a copy of the scp binary locally to use the scp feature
```
(Works in Git bash on Windows)

[Part 5](https://docs.docker.com/get-started/part5/#adding-a-new-service-and-redeploying):
Nit: Some sample command lines need $ at line start. Also in Part 4.

"Check the results on `http://localhost`. The host IP address instead? Localhost didn't work for me.
[Persisting data](https://docs.docker.com/get-started/part5/#persisting-data)

Up to Part 6, everything's fine, but things get confusing when your topic vectors the reader to the Docker Cloud content.

*Docker Cloud topics*

The "What's next?" link goes to the Docker Cloud "Getting started" tutorial:

"You’re ready to start using Microsoft Azure as the infrastructure provider for Docker Cloud! If you came here from the tutorial, click [here to continue the tutorial and deploy your first node.](https://docs.docker.com/docker-cloud/infrastructure/link-azure/)."

Looks like by design, but a bit confusing. I was expecting, naively, to return to the original topic. Now I've dropped into the middle of a different tutorial.

**Deploy to cloud** button doesn't work: "Unable to load the requested stackfile"
[Create a stack in Docker Cloud](https://docs.docker.com/docker-cloud/infrastructure/ssh-into-a-node/#create-a-stack-in-docker-cloud)

Then it's down the rabbit hole to get your ARN:

[Link to Amazon Web Services to create Swarms](https://docs.docker.com/docker-cloud/cloud-swarm/link-aws-swarm/#create-a-dockercloud-swarm-role-role-with-an-embedded-policy)
	3. Select Role for Cross-Account Access, and in the submenu that opens select **Allows IAM users from a 3rd party AWS account to access this account.**
Now reads Allows IAM users from a 3rd party AWS account to access this account **and enforces use of External ID.**

7. On the next screen, do not select a policy. Click **Next**.
UI is now **Next Step**.

15. Click **Create Policy**.
UI Is now **Apply Policy**

[Connect to a swarm through Docker Cloud](https://docs.docker.com/docker-cloud/cloud-swarm/connect-to-swarm/)
Couldn't get the Docker Cloud swarm client to work on PS or Git Bash, so I had to spin up a docker-machine. But the redis service won't start. Maybe I missed that step you mentioned?

```bash
docker@boot2docker:~$ docker stack ps getstartedlab
ID                  NAME                         IMAGE                                 NODE                                          DESIRED STATE       CURRENT STATE                ERROR                              PORTS
krtn08el3if6        getstartedlab_redis.1        redis:latest                          ip-172-31-12-196.us-west-2.compute.internal   Ready               Rejected 4 seconds ago       "invalid mount config for type…"
rk2cotwr11cp         \_ getstartedlab_redis.1    redis:latest                          ip-172-31-24-214.us-west-2.compute.internal   Shutdown            Rejected 9 seconds ago       "invalid mount config for type…"
sb4u172w1kmn         \_ getstartedlab_redis.1    redis:latest                          ip-172-31-40-174.us-west-2.compute.internal   Shutdown            Rejected 13 seconds ago      "invalid mount config for type…"
q6twssgk38en         \_ getstartedlab_redis.1    redis:latest                          ip-172-31-12-196.us-west-2.compute.internal   Shutdown            Rejected 18 seconds ago      "invalid mount config for type…"
grbqpazr0vse         \_ getstartedlab_redis.1    redis:latest                          ip-172-31-40-174.us-west-2.compute.internal   Shutdown            Rejected 24 seconds ago      "invalid mount config for type…"
```

*Back to Get Started*

Because the Get Started topic uses storage, we need to turn on disk sharing, which on Windows means that we gotta open port 445 on the firewall. [Shared drives](https://docs.docker.com/docker-for-windows/#shared-drives)

**Comment by javacraft** [comment] 2017-05-01 09:02
I can confirm Part 4 above, that `docker-machine scp` does not work in PowerShell 5.1b15063r138

    PS R:\Docker\samples\python-dev> docker-machine --version
    docker-machine.exe version 0.10.0, build 76ed2a6
    PS R:\Docker\samples\python-dev> docker --version
    Docker version 17.03.1-ce, build c6d412e
    PS R:\Docker\samples\python-dev> docker-machine scp docker-compose.yml myvm1:~
    You must have a copy of the scp binary locally to use the scp feature

but does work in Git Bash for Windows (thanks for the tip @JimGalasyn)

**Comment by joaofnfernandes** [comment] 2017-08-22 21:58
@JimGalasyn I'm assigning this back to you. Hopefully this went full circle and you can now fix the things that confuse new users 🛠

**Comment by friism** [comment] 2017-09-08 16:21
My comments would be:

> In PowerShell, docker-machine scp fails

This part of the guide should be rewritten to use the docker api from the host, instead of copying compose files hither and didther. That should simplify the guide.

> Nit: Some sample command lines need $ at line start. Also in Part 4.

IMO they should be removed everywhere since the make it difficult to copy-paste from the docs

> "Check the results on http://localhost. The host IP address instead? Localhost didn't work for me.

Yes, if you're using docker-machine it has to be `docker-machine ip` I suppose

**Closed** 2017-09-23 01:55 UTC
Labels: area/tutorials, priority/P4-Nice to Have
