### ISSUE TITLE
Wrong content under Communicate between a container and a swarm service

### ISSUE THREAD

**Issue by amaranand** [docker/docker.github.io#15384] opened 2022-08-14 04:31 UTC
File: [network/network-tutorial-overlay.md](https://docs.docker.com/network/network-tutorial-overlay/)

Under section, Communicate between a container and a swarm service

The details show only communication among containers in a bridge network and does not show communication of container to Service (overlay network), please check. thanks !

**Comment by craig-osterhout** [comment] 2022-08-18 20:20
Thanks for sharing the issue. Closing as duplicate of https://github.com/docker/docker.github.io/issues/8387

**Closed by craig-osterhout** 2022-08-18 20:20 UTC
Labels: area/Networking
