### ISSUE TITLE
doc improvement suggestion

### ISSUE THREAD

**Issue by nankingrider** [docker/docker.github.io#14464] opened 2022-03-29 08:04 UTC
File: [network/network-tutorial-overlay.md](https://docs.docker.com/network/network-tutorial-overlay/)

HI, the content below this title "Communicate between a container and a swarm service[🔗](https://docs.docker.com/network/network-tutorial-overlay/#communicate-between-a-container-and-a-swarm-service)"

has nothing to do with it ... maybe a mislocation, please check
thanks . !

**Comment by craig-osterhout** [comment] 2022-08-18 20:22
Thanks for sharing the issue. Closing as duplicate of https://github.com/docker/docker.github.io/issues/8387

**Closed by craig-osterhout** 2022-08-18 20:22 UTC
Labels: area/Docs UX
