### ISSUE TITLE
Getting Started - Part 4 - Step 6 - Not working!

### ISSUE THREAD

**Issue by allenross356** [docker/docker.github.io#14678] opened 2022-05-06 13:38 UTC
File: [get-started/04_sharing_app.md](https://docs.docker.com/get-started/04_sharing_app/)

Everything, all the steps, from Part 1 to Part 4 are working as expected, except the last step of part 4.

Part 4 - Step 6.

When I click the click the 3000 badge, a new tab opens, which keeps on loading forever until it dies after a few minutes.

I repeated the steps from Part 1 to Part 4, 3 times, exactly as provided.

Same result on all 3 times.

**Comment by craig-osterhout** [comment] 2022-05-06 16:45
Hi @allenross356, 

It may have been a temporary issue with labs.play-with-docker. I went through and I was unable to duplicate the problem. You can try the troubleshooting steps below to narrow down where the problem is located. If you find any errors in the documentation, please let us know. 

1. Verify that the image is functioning correctly.
You can verify this if you successfully connect to the container locally in Part 3- Start the updated app container (https://docs.docker.com/get-started/03_updating_app/#start-the-updated-app-container).

3. Next, verify that your image exists in the repository that you created on docker hub and that it is the same image you tested on your local machine. https://hub.docker.com/

4. Next, verify that there is not an issue with labs.play-with-docker or your network connection by running a different image on labs.play-with-docker.
For example, on labs.play-with-docker.com, run `docker run -dp 3000:80 docker/getting-started` and try to connect through port 3000 of that verified image.

Please try out the steps and let us know the results.

If you need more support to troubleshoot the issue, please try the Docker Community Slack at https://dockercommunity.slack.com/
If you have a Pro, Team, or Business subscription, please contact your commercial support or sales contact.

**Comment by craig-osterhout** [comment] 2022-05-18 21:38
Closing this issue. If an issue exists in the docs, please let us know.

**Closed by craig-osterhout** 2022-05-18 21:38 UTC
Labels: status/need-more-info
