### ISSUE TITLE
Recommend explicity configuring storage driver to be used by Docker Engine in production

### ISSUE THREAD

**Issue by mataneja** [docker/docker.github.io#6431] opened 2018-04-11 23:37 UTC
Use a `daemon.json` (`{"storage-driver":"overlay2"}`) to configure the storage driver instead of relying on automatic selection. Doing so excludes external factors (such as, changes to default configurations of the host)

**Comment by gbarr01** [comment] 2018-04-12 15:39
@thaJeztah thoughts?

**Comment by thaJeztah** [comment] 2018-04-12 23:06
Yes, this comes from a discussion on Slack; the first time the daemon starts (i.e., on a fresh install with no data in `/var/lib/docker`), it attempts to auto-detect the most suitable storage driver for the host it's running on. It does so by going through the list of storage-drivers and, for each driver, check if the requirements are met:

- if requirements are met, the storage for that driver is initialized and from then on, the daemon will use that storage driver.
- if requirements are _not_ met, it continues with the next driver in the list until it finds a suitable one.

For Docker 17.06, the order in which drivers that are tried (see [`daemon/graphdriver/driver_linux.go`](https://github.com/docker/docker-ce/blob/17.06/components/engine/daemon/graphdriver/driver_linux.go#L54-L63)) is:

```go
// Slice of drivers that should be used in an order
priority = []string{"aufs", "btrfs", "zfs", "overlay2", "overlay", "devicemapper", "vfs"}
```

For later versions, overlay2 (now that it has matured) has been promoted the [order is slightly different](https://github.com/docker/docker-ce/blob/18.03/components/engine/daemon/graphdriver/driver_linux.go#L50-L51):

```go
// List of drivers that should be used in an order
priority = "btrfs,zfs,overlay2,aufs,overlay,devicemapper,vfs"
```


While auto-detection/selection is great to get you going (it allows you to run Docker with minimal or no configuration, and it will give you a useful default), as an operator, I should be in control over what driver is used, to make sure Docker always runs with the same specifications. There are subtle differences between storage-drivers (performance, sometimes slightly differences in behavior), so I should not rely on automatic-detection if I want a reproducible environment when deploying new machines. 

Examples where automatic detection may give you a different storage driver:

- Changes in kernel configuration by cloud providers: `aufs` previously required installation of some kernel modules, and those may now be installed by default.
- Changes in kernel; recent RHEL/CentOS kernel updates added support for overlay2
- Improvement in detection for supported drivers (recent Docker CE and EE releases are now able to detect support for overlay2 in RHEL/CentOS kernels, without requiring the user to disable a kernel-version check).
- Changes in prioritization in updated versions of Docker (see the code samples above)


For reasons above, in production setups, we should always recommend explicit configuration over automatic selection.

Note that this only affects what's being selected on a _fresh_ install: existing installations will never automatically switch to a different storage-driver.

**Comment by L-Hudson** [comment] 2019-01-02 16:53
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Closed by L-Hudson** 2019-01-02 16:53 UTC
Labels: area/storage
