### ISSUE TITLE
Lacking documentation for swarm service placement constraints

### ISSUE THREAD

**Issue by alexmavr** [docker/docker.github.io#2241] opened 2017-03-09 22:58 UTC
### Problem description
In https://docs.docker.com/engine/swarm/services/#control-service-scale-and-placement:

```
Service constraints let you set criteria for a node to meet before the scheduler deploys a service to the node. You can apply constraints to the service based upon node attributes and metadata or engine metadata. For more information on constraints, refer to the docker service create CLI reference.
```

However the CLI reference at https://docs.docker.com/engine/reference/commandline/service_create/ only mentions:

```
--constraint	 	Placement constraints
```

I had to go to https://github.com/docker/swarmkit/blob/fb654e9afa426579dc0ce14bf51a80db2c18286e/manager/constraint/constraint.go

### Problem location
URLs included above

### Project version(s) affected
I don't think any versions had placement constraint docs

### Suggestions for a fix
Make sure they are documented

**Comment by mbentley** [comment] 2017-03-10 16:58
Related to https://github.com/docker/docker.github.io/issues/1981

**Comment by joaofnfernandes** [comment] 2017-03-14 22:56
Closing as duplicate of #1981.

**Comment by erikbgithub** [comment] 2017-07-31 13:06
what is solved about this issue? there's still no documentation? that's how I ended up here.

**Comment by joaofnfernandes** [comment] 2017-07-31 21:24
@erikbgithub you can find some docs about placement constraints [here](https://docs.docker.com/engine/reference/commandline/service_create/#specify-service-constraints-constraint) and [here](https://docs.docker.com/engine/reference/commandline/node_update/#add-label-metadata-to-a-node).

**Comment by plexirik** [comment] 2017-08-05 09:02
@joaofnfernandes In your first link I can't find anything for placement constraints, only for placement prefs. constraints only are explained with two words: "placement constraints". The second link doesn't contain the word "placement" at all. Maybe you know how to use the described stuff there to actually make placement constraints happen, because you used it in many different usecases. I haven't, so I'm not able to use a very general description to apply random features for that usecase. That's what documentation is therefore, to give examples for people who are not experienced enough to use the `--help` alone. Would you agree?

**Comment by erikbgithub** [comment] 2017-08-05 09:04
@joaofnfernandes In your first link I can't find anything for placement constraints, only for placement prefs. constraints only are explained with two words: "placement constraints". The second link doesn't contain the word "placement" at all. Maybe you know how to use the described stuff there to actually make placement constraints happen, because you used it in many different usecases. I haven't, so I'm not able to use a very general description to apply random features for that usecase. That's what documentation is therefore, to give examples for people who are not experienced enough to use the --help alone. Would you agree?

**Comment by joaofnfernandes** [comment] 2017-08-07 18:30
Based on the feedback above I'm reopening this issue.
It seems that we have documentation about placement constraints but it is:
* spread all over the place
* not easy to understand by new users

Having a single article that describes what are placement constraints, why should you care, and how to use them with Docker, would really help out a lot of people.
@erikbgithub thanks for the feedback!

**Closed** 2017-10-23 23:18 UTC
Labels: area/engine, priority/P0-catastrophic
