### ISSUE TITLE
`docker container logs` returns all logs even with `max-size` and `max-file` set.

### ISSUE THREAD

**Issue by trapier** [docker/docker.github.io#4127] opened 2017-08-08 20:00 UTC
### Problem description
https://docs.docker.com/engine/admin/logging/json-file/#options states:
> Note: If max-size and max-file are set, docker logs only returns the log lines from the newest log file.

This no longer seems to be the case.

Started a chatty container named `test-json-file-rotation` with `max-size` 1 and `max-file` 3, then stopped it after a while.  This was the state of modification time and sizes of the log files.  Note that `*-json.log` is the "newest":

    [root@node02 ~]# stat -c'%y %s %n' /var/lib/docker/containers/$(docker inspect --format {{.Id}} test-jsonfile-rotation)/*log*
    2017-08-08 19:39:43.128621625 +0000 411112 /var/lib/docker/containers/1e5572b03b65e263163aab4b359caa3431e6966d60d5d707939b362d2f90c30f/1e5572b03b65e263163aab4b359caa3431e6966d60d5d707939b362d2f90c30f-json.log
    2017-08-08 19:39:26.567623700 +0000 1000032 /var/lib/docker/containers/1e5572b03b65e263163aab4b359caa3431e6966d60d5d707939b362d2f90c30f/1e5572b03b65e263163aab4b359caa3431e6966d60d5d707939b362d2f90c30f-json.log.1
    2017-08-08 19:38:46.497628720 +0000 1000047 /var/lib/docker/containers/1e5572b03b65e263163aab4b359caa3431e6966d60d5d707939b362d2f90c30f/1e5572b03b65e263163aab4b359caa3431e6966d60d5d707939b362d2f90c30f-json.log.2

Looking at the first line of every log file, we find the following:

    [root@node02 ~]# head -n1 /var/lib/docker/containers/$(docker inspect --format {{.Id}} test-jsonfile-rotation)/*.log*
    ==> /var/lib/docker/containers/1e5572b03b65e263163aab4b359caa3431e6966d60d5d707939b362d2f90c30f/1e5572b03b65e263163aab4b359caa3431e6966d60d5d707939b362d2f90c30f-json.log <==
    {"log":"Tue Aug 8 19:37:25 UTC 2017 I | http: TLS handshake error from 10.1.0.6:53558: EOF\n","stream":"stdout","time":"2017-08-08T19:39:26.575229037Z"}

    ==> /var/lib/docker/containers/1e5572b03b65e263163aab4b359caa3431e6966d60d5d707939b362d2f90c30f/1e5572b03b65e263163aab4b359caa3431e6966d60d5d707939b362d2f90c30f-json.log.1 <==
    {"log":"Tue Aug 8 19:37:25 UTC 2017 I | http: TLS handshake error from 10.1.0.6:53558: EOF\n","stream":"stdout","time":"2017-08-08T19:38:46.504944938Z"}

    ==> /var/lib/docker/containers/1e5572b03b65e263163aab4b359caa3431e6966d60d5d707939b362d2f90c30f/1e5572b03b65e263163aab4b359caa3431e6966d60d5d707939b362d2f90c30f-json.log.2 <==
    {"log":"Tue Aug 8 19:37:25 UTC 2017 I | http: TLS handshake error from 10.1.0.6:53558: EOF\n","stream":"stdout","time":"2017-08-08T19:38:06.1335379Z"}
    [root@node02 ~]# docker logs test-jsonfile-rotation |head -n1
    Tue Aug 8 19:37:25 UTC 2017 I | http: TLS handshake error from 10.1.0.6:53558: EOF

Check the first line returned by `docker logs`, using `--timestamp` to provide a unique id for the message.  The following message is from `*-json.log.2`, which is the _oldest_ log file:

    [root@node02 ~]# docker logs --timestamps test-jsonfile-rotation |head -n1
    2017-08-08T19:38:06.133537900Z Tue Aug 8 19:37:25 UTC 2017 I | http: TLS handshake error from 10.1.0.6:53558: EOF

Validate `docker logs` provides coverage for from the other log files as well:

    [root@node02 ~]# docker logs --timestamps test-jsonfile-rotation |grep -l 19:38:46
    (standard input)
    [root@node02 ~]# docker logs --timestamps test-jsonfile-rotation |grep -l 19:39:26
    (standard input)

### Problem location

https://docs.docker.com/engine/admin/logging/json-file/#options

### Project version(s) affected

According to the git log, the current note in the documentation was added by 9b782d3af322bd8d9cf857d63eb7f2e0fe484c90, so some time between June 2015 and the present the behavior changed.  Do not know which Docker version it changed in. "present" version in this case is 17.03.2-ee-5.

### Suggestions for a fix

Remove this note from the json-file admin logging guide.

**Comment by mstanleyjones** [comment] 2017-09-11 20:53
Is this a product bug? @nishanttotla

**Comment by nishanttotla** [comment] 2017-09-11 21:04
Ping @dperny who knows a lot more about logs.

**Comment by dperny** [comment] 2017-09-11 21:20
it's an issue in the driver, deeper in the stack than i've worked. i'd say ask @cpuguy83 if he knows before i start digging in to see if it's a product bug, but he's a bit busy right now.

(that is if he doesn't know off hand one way or the other, i'll figure out what the problem is)

**Comment by mstanleyjones** [comment] 2017-09-11 21:24
He's cleaning up from Irma so he's out of pocket.

**Comment by mstanleyjones** [comment] 2017-09-11 21:25
Anyway @dperny if you can confirm it's not a docs issue, maybe we can open the issue elsewhere and close this one? Maybe ping this one in that upstream issue so that the OP can watch.

**Comment by dperny** [comment] 2017-09-11 21:56
Looks to me like this is just a docs issue. Relevant code is here: https://github.com/moby/moby/blob/master/daemon/logger/jsonfilelog/read.go#L56

This is if config.Tail != 0, and the default tail value at the CLI level is `all` so an unadorned `logs` command follows this branch.

Working as intended.

**Comment by cpuguy83** [comment] 2017-09-18 12:45
Yeah, this just looks like a docs issue.

**Comment by mstanleyjones** [comment] 2017-09-18 18:56
Thanks, I'll look at how to clarify this.

**Closed** 2017-10-04 23:53 UTC
Labels: area/engine, Tech Review: Needed
