### ISSUE TITLE
Azure storage setting values need to be documented

### ISSUE THREAD

**Issue by jasonbivins** [docker/docker.github.io#9593] opened 2019-10-08 02:51 UTC
File: [datacenter/dtr/2.0/configure/config-storage.md](https://docs.docker.com/datacenter/dtr/2.0/configure/config-storage/)

```
Azure settings

Set the “Account name”, “Account key”, “Container”, and “Realm” on the Azure storage backend page.
```
Specifically in my case I'm looking for an explanation of where to get the `“Container”, and “Realm”` values

This section contains a link to this page:  https://docs.docker.com/registry/configuration/#azure
The page it links to is huge - and the settings I'm looking for are not even mentioned here.
Azure is mentioned on this page once in the storage driver options
In the storage driver options there is another link - https://github.com/docker/docker.github.io/blob/master/registry/storage-drivers/azure.md

**Comment by lena-larionova** [comment] 2019-11-20 21:34
Looks like the issue is that the DTR team updated the registry/configuration document a long time ago and no one ever noticed (it's maintained in their repo, not here). 

The storage driver options are actually on docs.docker.com under Reference, so I just updated the doc you originally landed on to point there: https://docs.docker.com/registry/storage-drivers/azure

**Comment by usha-mandya** [comment] 2020-07-01 11:07
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this issue here for that reason. Feel free to continue the conversation after I close.

**Closed by usha-mandya** 2020-07-01 11:07 UTC
Labels: DTR
