### ISSUE TITLE
404 link to daemon repo

### ISSUE THREAD

**Issue by bofm** [docker/docker.github.io#2108] opened 2017-03-04 18:17 UTC
File: [engine/admin/logging/log_tags.md](https://docs.docker.com/engine/admin/logging/log_tags/)

logging_context link is invalid

**Comment by scjane** [comment] 2017-04-17 05:20
#dibs

**Comment by shubheksha** [comment] 2017-04-17 12:10
This issue is a duplicate of #2300 and #2430. It can be closed.

**Comment by johndmulhausen** [comment] 2017-04-18 15:54
Thanks @scjane and @shubheksha. 25 points to @shubheksha for identifying the duplicate.

**Closed by johndmulhausen** 2017-04-18 15:54 UTC
Labels: area/engine, hackathon, points/25
