### ISSUE TITLE
Add sudo to instructions where required

### ISSUE THREAD

**Issue by pzi123** [docker/docker.github.io#1610] opened 2017-02-11 09:19 UTC
File: [engine/getstarted/step_one.md](https://docs.docker.com/engine/getstarted/step_one/)

CLI instructions are missing 'sudo' for each command. The $ prompt indicates non root user and without sudo all you get is permission denied.

**Comment by JimGalasyn** [comment] 2017-03-27 23:25
Thank you for your feedback. I'm unable to reproduce this issue on OS X. Can you provide details on your OS environment?

**Comment by JimGalasyn** [comment] 2017-04-01 17:32
If you're satisfied with this resolution, I'll go ahead and close this issue.

**Comment by pzi123** [comment] 2017-04-01 20:12
The CLI instructions I was commenting on were about Linux/UNIX environment. I guess you need the OS like that to work on that fix.  You also need to know what 'sudo' is.

**Comment by JimGalasyn** [comment] 2017-04-03 15:30
Very good, thank you for the clarification. I'll add a note reminding Linux users that they may need to prepend "sudo" for commands to work.

**Comment by prashant171992** [comment] 2017-04-18 16:49
@pzi123 this page is deleted now, though I made the changes and raised a PR but its not useful now I think . Do u want to close this issue now or require to do the same thing at new place ?

**Comment by londoncalling** [comment] 2017-04-18 18:51
@pzi123 Yes let's close the issue and the PR. I can do that. Thanks!

@johndmulhausen @mstanleyjones Let's still credit @pzi123 for the points on PR #2834 - it was related to the superseded basics Getting Started.

**Closed** 2017-04-18 18:51 UTC
Labels: area/engine, hackathon, points/250

**Comment by prashant171992** [comment] 2017-04-18 18:54
@londoncalling did u try to call me in ur above comment ? I'm @prashant171992

**Comment by londoncalling** [comment] 2017-04-18 19:42
@prashant171992 yes, @mstanleyjones closed it as she said it's not needed anymore, but you whomever fixed it still gets the points for it. I thought it was @pzi123 but it might have been you. We will settle it out after the Hackathon when we have time to go through these more thoroughly. Cool?
