### ISSUE TITLE
Link "Docker Enterprise Edition" not working in Chrome v62 and v63

### ISSUE THREAD

**Issue by gnschenker** [docker/docker.github.io#5498] opened 2017-12-13 08:22 UTC
The menu on the left hand side of the page has a non working first link "Docker Enterprise Edition" when using Chrome in either version 62 or 63 on MacBookPro. 
In Firefox and Safari the link works and expands the subtopics.

File: [manuals.md](https://docs.docker.com/manuals/), CC @johndmulhausen

**Comment by joaofnfernandes** [comment] 2017-12-13 18:51
I can't reproduce this with a Macbook running Chrome 62. Can't you check the develop tools console to see if there's any error? Also, are you using any pop-up blockers or anything like that?

**Comment by johndmulhausen** [comment] 2017-12-16 00:19
Duplicate of #5511

**Closed by johndmulhausen** 2017-12-16 00:19 UTC
Labels: area/docsite
