### ISSUE TITLE
Compose Example doesent work on Windows 10

### ISSUE THREAD

**Issue by crydotsnake** [docker/docker.github.io#12254] opened 2021-02-04 20:16 UTC
https://docs.docker.com/compose/gettingstarted/

If i try the example and run `docker-compose up` i get always this error message:

```bash
PS C:\Development\flask-app> docker-compose up
Starting flask-app_web_1   ... done
Starting flask-app_redis_1 ... done
Attaching to flask-app_redis_1, flask-app_web_1
redis_1  | 1:C 04 Feb 2021 20:12:32.209 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1  | 1:C 04 Feb 2021 20:12:32.210 # Redis version=6.0.10, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1  | 1:C 04 Feb 2021 20:12:32.210 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1  | 1:M 04 Feb 2021 20:12:32.212 * Running mode=standalone, port=6379.
redis_1  | 1:M 04 Feb 2021 20:12:32.212 # Server initialized
redis_1  | 1:M 04 Feb 2021 20:12:32.212 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1  | 1:M 04 Feb 2021 20:12:32.212 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo madvise > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled (set to 'madvise' or 'never').
redis_1  | 1:M 04 Feb 2021 20:12:32.213 * Ready to accept connections
web_1    |  * Serving Flask app "main.py"
web_1    |  * Environment: production
web_1    |    WARNING: This is a development server. Do not use it in a production deployment.
web_1    |    Use a production WSGI server instead.
web_1    |  * Debug mode: off
web_1    | Usage: flask run [OPTIONS]
web_1    |
web_1    | Error: Could not import "main".
flask-app_web_1 exited with code 2
```

Its also weird that he says: `serving Flask App "main.py"`. But my file is called `àpp.py`.

Dockerfile:

```dockerfile
FROM python:3.7-alpine
WORKDIR /code
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
RUN apk add --no-cache gcc musl-dev linux-headers
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 5000
COPY . .
CMD ["flask", "run"]
```

docker-compose.yml:

```yaml
version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"

  redis:
    image: "redis:alpine"    
```

app.py:

```python
import time

import redis
from flask import Flask

app = Flask(__name__)
cache = redis.Redis(host='redis', port=6379)

def get_hit_count():
    retries = 5
    while True:
        try:
            return cache.incr('hits')
        except redis.exceptions.ConnectionError as exc:
            if retries == 0:
                raise exc
            retries -= 1
            time.sleep(0.5)

@app.route('/')
def hello():
    count = get_hit_count()
    return 'Hello World! I have been seen {} times.\n'.format(count)
```

And in VSCode he says also:

![Code_UUer1yCIFo](https://user-images.githubusercontent.com/39345336/106950339-8efc7b80-672e-11eb-9a4d-09225290f2c6.png)

**Comment by craig-osterhout** [comment] 2022-05-02 22:58
Thanks for sharing this issue. As this issue is old, some context may have changed. I'm unable to reproduce the issue when following the docs and it appears to be specific to your environment. If you changed "main.py" to "app.py" in your dockerfile after running docker-compose up, make sure you remove the old images and volumes.

 As this is not an issue in the documentation, I'm closing this issue. If you need further support, you can try the Docker Community Forums.

**Closed by craig-osterhout** 2022-05-02 22:58 UTC
