### ISSUE TITLE
update UCP/DTR system requirements page

### ISSUE THREAD

**Issue by nicolaka** [docker/docker.github.io#3080] opened 2017-04-26 17:16 UTC
### Problem description

https://docs.docker.com/datacenter/ucp/2.1/guides/admin/install/system-requirements/
still uses CS engine.

Also need to add requirement to have block device for devicemapper if using centos/rhel.

### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by joaofnfernandes** [comment] 2017-04-26 18:30
Duplicate of #2517, and #2769

**Closed by joaofnfernandes** 2017-04-26 18:30 UTC
