### ISSUE TITLE
Teach long syntax for --publish

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#3948] opened 2017-07-21 18:45 UTC
File: [engine/reference/commandline/service_create.md](https://docs.docker.com/engine/reference/commandline/service_create/), CC @mstanleyjones

This reference teaches how to publish port, but doesn't explain the new and more intuitive syntax for `--publish`

```
docker service create --name wp \
--publish mode=host,target=80,published=8000 \
wordpress
```

The new syntax is kind of covered at https://docs.docker.com/engine/swarm/services/#publish-ports, but we should also clean that one a bit and start promoting the longer syntax.

**Comment by mbentley** [comment] 2017-08-13 22:18
It would be ideal if we had a table format similar to the mount parameters: https://docs.docker.com/engine/reference/commandline/service_create/#add-bind-mounts-or-volumes

I was looking for the publish syntax again today and couldn't find it.

**Comment by joaofnfernandes** [comment] 2017-08-14 17:13
@thaJeztah this seems to be a duplicate of #3913. Can you confirm, and if so close this one?

**Comment by thaJeztah** [comment] 2017-08-14 21:12
Ah, yes, this is a duplicate of https://github.com/docker/docker.github.io/issues/3913 thanks for noticing 👍

**Closed by thaJeztah** 2017-08-14 21:12 UTC
