### ISSUE TITLE
404 at /engine/installation/linux/docker-ce/debian/

### ISSUE THREAD

**Issue by bean5** [docker/docker.github.io#5835] opened 2018-01-26 19:33 UTC
URL: /engine/installation/linux/docker-ce/debian/

*Expected*
A page with instructions on how to install Docker on debian renders.

*Actual*
On Linux (firefox), the following link is an infinite loop. On Windows (chrome), the page gives a 404.

*Background*
Various pages link to the following URL for instructions on how to install Docker CE for Debian.

**Comment by joaofnfernandes** [comment] 2018-01-26 21:33
Thanks for reporting @bean5! Closing as duplicate of #5837

**Closed by joaofnfernandes** 2018-01-26 21:33 UTC

**Comment by bean5** [comment] 2018-01-28 02:18
Huh, I had checked for duplicates. Must have missed that one.

Thank you!
