### ISSUE TITLE
docs site sidebar nav section titles reset the window location on click

### ISSUE THREAD

**Issue by carolineartz** [docker/docker.github.io#658] opened 2016-11-20 03:11 UTC
### Problem description

I've been navigating all around the docs site -- it's great. One thing that has been frustrating is the browser window "headbutting" behavior when clicking a section title in the left navigation tree. 

On click, section titles expand reveal its pages (and subsections of pages). It's very jarring and confusing because the section the was just revealed is likely out of the viewport and you need to scroll and find the location you were browsing for in the tree. Multiple subsections can be expanded at once, so this quickly becomes unmanageable. 

The problem lies in that the titles themselves are links with a location of `<current page>/#`, forcing the window location to the top when clicked. 

### Problem location

I saw a problem on the following URL: https://docs.docker.com/ and any of its child pages.

### Suggestions for a fix

This can be fixed through various approaches... But, I was able to pretty easily get the behavior I would expect by changing the `a.expand-menu` tag to a `span` tag in the `tree.html` template and adjusting the styles in `documentation.css` in line with that tag change. (The change to `span` vs. other to limit necessary changes to css.) I'm happy to take out a PR.

**Comment by johndmulhausen** [comment] 2016-11-22 01:36
Duplicate of issue #635 -- but thanks for the thoughtful issue and the suggestions for a fix @carolineartz. This issue should be all fixed. :)

**Comment by johndmulhausen** [comment] 2017-04-04 20:49
Closing this oldie. Thanks! :)

**Closed by johndmulhausen** 2017-04-04 20:49 UTC
