### ISSUE TITLE
Feedback for: compose/compose-file/index.md

### ISSUE THREAD

**Issue by drnybble** [docker/docker.github.io#1656] opened 2017-02-14 14:40 UTC
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/)

The ".env file" hyperlink results in a 404.

https://docs.docker.com/sorry/#/compose/compose-file/env-file/

**Comment by JimGalasyn** [comment] 2017-04-04 23:49
Dupe of #1670 .

**Closed by JimGalasyn** 2017-04-04 23:49 UTC
