### ISSUE TITLE
Issue with python install when following tutorial

### ISSUE THREAD

**Issue by oceloteye** [docker/docker.github.io#13822] opened 2021-11-10 02:52 UTC
File: [get-started/02_our_app.md](https://docs.docker.com/get-started/02_our_app/)

 > [2/5] RUN apk add --no-cache python g++ make:
#11 0.318 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
#11 0.688 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
#11 0.846 ERROR: unable to select packages:
#11 0.869   python (no such package):
#11 0.869     required by: world[python]

Fixed by using the following contents for the Dockerfile

# syntax=docker/dockerfile:1
FROM node:12-alpine
RUN apk add --no-cache python3 py3-pip
EXPOSE 8080
WORKDIR /app
COPY . .
RUN yarn install --production
CMD ["node", "src/index.js"]

**Comment by usha-mandya** [comment] 2021-11-12 17:03
Let me go ahead and close this ticket, but feel free to continue the conversation if the issue is not resolved 👍

**Closed by usha-mandya** 2021-11-12 17:03 UTC
Labels: area/get-started
