### ISSUE TITLE
Where is contexts stored inside dcoker?

### ISSUE THREAD

**Issue by vitormcruz** [docker/docker.github.io#7651] opened 2018-11-10 02:07 UTC
File: [engine/reference/commandline/build.md](https://docs.docker.com/engine/reference/commandline/build/)

The documentation isn't clear whether the context is accessible from docker build, it says it send the context withing a tar file, but don't tell where I should look to find it. Copy command link was broken at the time I read it, but I found information elsewhere ant it make the image retain the context, which contradicts the doc in questions that says the context is deleted at the image build end. 

At the end I learned the difficult way that the only way to copy context and leave it out of the image is using multi-stage docker file. If that is the case, this should be explained in the referenced page.

**Comment by craig-osterhout** [comment] 2022-05-26 17:07
Thanks for sharing this issue. This particular content is maintained in an upstream repo. Since this issue is dated, I'm not sure if it is still applicable. If the issue is still applicable, please help create an issue or PR in the source repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
Closing this as unable to fix in this repo.

**Closed by craig-osterhout** 2022-05-26 17:07 UTC
