### ISSUE TITLE
Document TaskTemplate > ContainerSpec > Hostname for /services/create and /services/update

### ISSUE THREAD

**Issue by sbrattla** [docker/docker.github.io#1531] opened 2017-02-06 22:19 UTC
The following is (part of a) valid JSON when creating or updating a service :

```
{
  "Name": "testservice",
  "TaskTemplate": {
    "ContainerSpec": {
      "Hostname": "stage01{{.Service.Name}}-{{.Node.ID}}"
```

There is no mention of `Hostname` in the [API v1.25 Reference](https://docs.docker.com/engine/api/v1.25/#operation/ServiceCreate).

**Comment by mstanleyjones** [comment] 2017-06-28 20:38
Duplicate of #1530

**Closed by mstanleyjones** 2017-06-28 20:38 UTC
Labels: area/engine
