### ISSUE TITLE
Add some directions on how to run the logging driver

### ISSUE THREAD

**Issue by FedericoPonzi** [docker/docker.github.io#10063] opened 2019-12-19 09:48 UTC
File: [engine/extend/plugins_logging.md](https://docs.docker.com/engine/extend/plugins_logging/)
It would be nice to have either a link or a section describing how to run the example logging driver, since also the linked example repo comes without a README. Thanks!

**Comment by craig-osterhout** [comment] 2022-05-25 22:15
Thanks for sharing this issue. This particular topic is maintained in an upstream repo. If the issue is still applicable, please help create an issue or a PR in the source repo at https://github.com/docker/cli/tree/master/docs/extend
Closing this issue as unable to fix in this repo.

**Closed by craig-osterhout** 2022-05-25 22:15 UTC
