### ISSUE TITLE
"Communicate between a container and a swarm service" needs to be updated.  It is a duplicate of the bridge.

### ISSUE THREAD

**Issue by zkSNARK** [docker/docker.github.io#9074] opened 2019-07-17 04:13 UTC
File: [network/network-tutorial-overlay.md](https://docs.docker.com/network/network-tutorial-overlay/)

**Comment by Mikuu** [comment] 2019-07-19 06:32
+1

**Comment by pluckhuang** [comment] 2019-09-26 13:33
the same #9046

**Comment by DavidSonoda** [comment] 2020-01-10 20:13
Please fix this as soon as possible. 

I looked for this tutorial for a long time and when I finally found it here it's just not related to the 'Communication between a container and a swarm service' at all. Does anyone have the correct tutorial?

**Comment by craig-osterhout** [comment] 2022-08-18 20:21
Thanks for sharing the issue. Closing as duplicate of https://github.com/docker/docker.github.io/issues/8387

**Closed by craig-osterhout** 2022-08-18 20:21 UTC
Labels: area/Networking
