### ISSUE TITLE
specify to use port 4000 when accessing VM IP address

### ISSUE THREAD

**Issue by gbooth27** [docker/docker.github.io#6981] opened 2018-07-02 21:35 UTC
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/)

I had connectivity trouble outlined in this comment: 
Having connectivity trouble?

Keep in mind that to use the ingress network in the swarm, you need to have the following ports open between the swarm nodes before you enable swarm mode:

Port 7946 TCP/UDP for container network discovery.
Port 4789 UDP for the container ingress network.

I found that if you specified port 4000 at the end of the IP address for the VM it would connect when it wasnt connecting before. but the page itself does not ever suggest that as a troubleshooting measure

**Comment by L-Hudson** [comment] 2019-01-02 18:52
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by aaronistheman** [comment] 2019-03-04 07:44
There's still no indication of the fix suggested by gbooth27 on said tutorial (https://docs.docker.com/get-started/part4/#deploy-your-app-on-the-swarm-cluster). I had to stumble across this thread to get through part 4 of the tutorial.

**Comment by sduslu** [comment] 2019-06-20 11:48
I agree, an indication stating that port 4000 has to be added to the IP address would be helpful. I found the solution here (https://forums.docker.com/t/how-to-open-port-7946-and-4789-in-a-vm-which-is-created-by-docker-machine/43422)

**Comment by craig-osterhout** [comment] 2022-04-28 19:51
Thanks for sharing the issue. It seems that the issue is no longer applicable in the current docs. Closing the issue. If you find that the issue still exists in another part of the documentation, please let us know.

**Closed by craig-osterhout** 2022-04-28 19:51 UTC
Labels: area/Networking
