### ISSUE TITLE
Compose, IPs in SAN for custom certificate

### ISSUE THREAD

**Issue by martencassel** [docker/docker.github.io#4597] opened 2017-09-12 16:25 UTC
File: [datacenter/ucp/2.2/guides/admin/configure/use-your-own-tls-certificates.md](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/configure/use-your-own-tls-certificates/), CC @jimgalasyn

This section says that for "compose" to work in the UCP Web UI, your own certificates must contain IP addresses of swarm nodes as SAN's.  

Does this mean that if i issue and upload my own UCP certificate i have to add SAN of domain names plus IP addresses of each UCP manager ? 

Or does it mean that i import my certs to UCP and later add IP's of UCP managers using the Web GUI ?  I also haven't this requirement anywhere else ? 

These documents never mentions this:
(https://docs.docker.com/datacenter/ucp/2.2/guides/admin/install/plan-installation/#use-an-external-certificate-authority) 

https://success.docker.com/Architecture/Docker_Reference_Architecture%3A_Docker_EE_Best_Practices_and_Design_Considerations

**Comment by JimGalasyn** [comment] 2017-10-13 21:49
Confirmed with Engineering that this is no longer necessary, removing.

**Comment by trapier** [comment] 2017-11-13 15:58
> Confirmed with Engineering that this is no longer necessary, removing.

@JimGalasyn: As of what version?  May have users on earlier UCP 2.2 versions that still run into this.

**Comment by JimGalasyn** [comment] 2017-11-13 17:25
@trapier I'm happy to add a note about specific versions. Do you know which version of UCP 2.2 has the change?

**Comment by trapier** [comment] 2017-11-13 17:42
Looks like 2.2.4 was the first version to ship the improvement.

https://github.com/docker/orca/issues/8351 fixed in https://github.com/docker/ui/pull/3248 incorporated into ucp by https://github.com/docker/orca/pull/9424.

**Comment by JimGalasyn** [comment] 2017-11-13 18:02
Cool, I'll add a note.

**Closed** 2018-06-03 11:31 UTC
Labels: area/ee, area/ucp
