### ISSUE TITLE
Feedback for: engine/reference/commandline/service_create.md

### ISSUE THREAD

**Issue by mightyroser** [docker/docker.github.io#2034] opened 2017-03-01 14:51 UTC
Although several pages (such as https://docs.docker.com/compose/compose-file/#/placement) indicate that the 'service create' page should include documentation on how to configure constraints the instructions seem to be missing.

File: [engine/reference/commandline/service_create.md](https://docs.docker.com/engine/reference/commandline/service_create/), CC: @mstanleyjones

**Comment by mstanleyjones** [comment] 2017-03-01 23:28
Duplicate of #1981

**Closed by mstanleyjones** 2017-03-01 23:28 UTC
