### ISSUE TITLE
Build the app’s container image

### ISSUE THREAD

**Issue by alihghaith1990** [docker/docker.github.io#13815] opened 2021-11-09 09:56 UTC
File: [get-started/02_our_app.md](https://docs.docker.com/get-started/02_our_app/)
the example is not working, full of errors (python, yarn, etc..) not suitable for a beginner

**Comment by thaJeztah** [comment] 2021-11-12 16:58
Thanks for reporting; I think this should be fixed by https://github.com/docker/docker.github.io/pull/13826, which is now published on docs.docker.com.

Let me go ahead and close this ticket, but feel free to continue the conversation if the issue is not resolved 👍

**Closed by thaJeztah** 2021-11-12 16:58 UTC
