### ISSUE TITLE
Unable to build with docker-compose

### ISSUE THREAD

**Issue by iamShantanu101** [docker/docker.github.io#3316] opened 2017-05-18 06:36 UTC
### Problem description

I am not able to run this with docker-compose up.
Here is what it shows on running docker-compose up:
```
$ docker-compose up

Starting dockergithubio_docs_1 ...
Starting dockergithubio_docs_1 ... done
Attaching to dockergithubio_docs_1
docs_1  | Configuration file: /usr/src/app/_config.yml
docs_1  | Configuration file: /usr/src/app/_config.yml
docs_1  |             Source: /usr/src/app
docs_1  |        Destination: /_site
docs_1  |  Incremental build: enabled
docs_1  |       Generating...
docs_1  |   Liquid Exception: Could not locate the included file 'library/adminer/github-repo' in any o
f ["/usr/src/app/samples"]. Ensure it exists in one of those directories and, if it is a symlink, does
not point outside your site source. in /_layouts/library.html
docs_1  | jekyll 3.3.1 | Error:  Could not locate the included file 'library/adminer/github-repo' in an
y of ["/usr/src/app/samples"]. Ensure it exists in one of those directories and, if it is a symlink, do
es not point outside your site source.
```

**Comment by AyushyaChitransh** [comment] 2017-05-22 07:13
I was looking at the commits and I found that pull request (#3291) is working and the merged pull immediately after that, (#3063) is not working. I am trying to figure out the changes required to be made to fix it.

**Comment by AyushyaChitransh** [comment] 2017-05-22 12:32
The problem is due to the [layout/library.html](https://github.com/docker/docker.github.io/blob/master/_layouts/library.html) which is processing the contents of [samples](https://github.com/docker/docker.github.io/blob/master/samples) folder. The pull request [Docker library import](#3063 ) is not yet ready to be merged. A workaround for this is to remove the samples folder.

**Comment by iamShantanu101** [comment] 2017-05-26 07:48
This is what I am getting after removing [samples](https://github.com/docker/docker.github.io/blob/master/samples) folder.

```
$ docker-compose up
Starting dockergithubio_docs_1 ...
Starting dockergithubio_docs_1 ... done
Attaching to dockergithubio_docs_1
docs_1  | /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/resolver.rb:366:in `block in ve
rify_gemfile_dependencies_are_found!': Could not find gem 'github-pages (= 137)' in any of the gem sourc
es listed in your Gemfile or available on this machine. (Bundler::GemNotFound)
docs_1  |       from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/resolver.rb:341:in `
each'
docs_1  |       from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/resolver.rb:341:in `
verify_gemfile_dependencies_are_found!'
docs_1  |       from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/resolver.rb:199:in `
start'
docs_1  |       from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/resolver.rb:181:in `
 `resolve'
docs_1  |       from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:174:in
 `specs'
docs_1  |       from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:233:in
 `specs_for'
docs_1  |       from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:222:in
 `requested_specs'
docs_1  |       from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:118:in `b
lock in definition_method'
docs_1  |       from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:19:in `se
tup'
docs_1  |       from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:99:in `setup'
docs_1  |       from /usr/local/bundle/gems/jekyll-3.3.1/lib/jekyll/plugin_manager.rb:36:in `require_fro
m_bundler'
docs_1  |       from /usr/local/bundle/gems/jekyll-3.3.1/exe/jekyll:9:in `<top (required)>'
docs_1  |       from /usr/local/bundle/bin/jekyll:22:in `load'
docs_1  |       from /usr/local/bundle/bin/jekyll:22:in `<main>'
dockergithubio_docs_1 exited with code 1
```

Looks like somethings wrong with github-pages gem?

**Comment by AyushyaChitransh** [comment] 2017-06-09 10:31
This seems to be machine specific issue that gem file is not available on you machine. For reference, you may take a look [here](https://github.com/jekyll/jekyll/issues/3103) and [here](https://github.com/jekyll/docker/issues/150). However, now my build is failing even after removing samples folder. The error given is:
`Liquid Exception: invalid byte sequence in US-ASCII in _layouts/redirect.html`
Also there were few warnings referring to [engine/swarm/services.md](https://github.com/docker/docker.github.io/blob/master/engine/swarm/services.md).
I am using `git reset --hard 919bc2c` to run docs on my local  machine.

**Comment by dailyherold** [comment] 2017-06-19 19:54
Experiencing the same thing on my machine @AyushyaChitransh. The commit you gave to reset to, worked as well.

**Comment by AyushyaChitransh** [comment] 2017-07-08 23:01
The problem is that samples folder includes a submodule and its contents are not cloned when a clone is preformed of this repository. 
So, before running `docker-compose up`, one needs to perform clone of library submodule from [docker-library/docs](https://github.com/docker-library/docs/tree/7d03e2198f07a2e95c6ab9c04d26f168dc8fa1e6).

Following  instructions can be used (required only for the first time):

```
cd docker.github.io/samples
git clone https://github.com/docker-library/docs.git
mv docs/* library/
rm -rf docs
cd library
git reset --hard 7d03e21
```

**Comment by thaJeztah** [comment] 2017-07-13 16:45
ping @johndmulhausen @mstanleyjones

**Comment by AyushyaChitransh** [comment] 2017-07-13 16:56
I was getting `Liquid Exception: invalid byte sequence in US-ASCII in _layouts/redirect.html` and on looking further into this, I came to know that it was caused by a plugin `jekyll-redirect-from`. I looked further [here](https://github.com/jekyll/jekyll-redirect-from/issues/139) and there someone walked the version chain of `jekyll-redirect-from` forward from 0.10.0 until it stopped working. It looks like the first version that has this error is:

gem install jekyll-redirect-from -v 0.12.0

Am not sure if this is my machine specific issue or is it included in the builds.

**Comment by mstanleyjones** [comment] 2017-07-13 17:01
Yeah, this is the same error I was experiencing. @johndmulhausen can you please pin the `jekyll-redirect-from` version at something earlier than 0.12.0?

**Comment by AyushyaChitransh** [comment] 2017-07-13 17:09
Another thing, I was looking in `dockerfile` and `docker-compose` file for something which would take care of the `library` submodule. Or if that has to be done manually, then we should probably mention about it in the setup instructions.

**Comment by stevenhanna6** [comment] 2017-07-14 23:46
Hopefully I did the pull request right, it's been awhile.

Bottom line is the builtin redirect.html has some weird unicode/ascii issue, they fixed it in the next version but that hasn't been released. You can generate your own redirect.html and avoid the bug completely, that's what this fix does.

Might be a good idea for a custom redirect anyways?

Hopefully it helps anyone, because as of now "docker-compose up" wont work with this bug.

**Closed** 2017-07-18 20:49 UTC
