### ISSUE TITLE
Issue with instructions for accessing the sample app on the Swarm

### ISSUE THREAD

**Issue by vkpopuri** [docker/docker.github.io#7522] opened 2018-10-16 01:44 UTC
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/)

After following the instructions for deploying on Docker Swarm, I tried accessing the sample application using http://<IP> but didn't work. It works with http://<IP>:4000 though. I think instructions need to be updated.

Thanks

**Comment by craig-osterhout** [comment] 2022-04-28 23:58
Thanks for sharing the issue. It seems that the issue is no longer applicable in the current docs. Closing the issue. If you find that the issue still exists in another part of the documentation, please let us know.
Related to #6981

**Closed by craig-osterhout** 2022-04-28 23:58 UTC
