### ISSUE TITLE
404 at /cadvisor

### ISSUE THREAD

**Issue by zhangchao1484** [docker/docker.github.io#12468] opened 2021-03-10 09:33 UTC
I found a broken link : https://docs.docker.com/cadvisor

**Comment by jerae-duffin** [comment] 2021-05-20 19:15
Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

**Comment by craig-osterhout** [comment] 2022-04-26 21:15
Thanks for sharing the issue. We are unable to reproduce the issue and are closing it due to insufficient information. If you still encounter the issue, please respond with the requested details.

**Closed by craig-osterhout** 2022-04-26 21:15 UTC
