### ISSUE TITLE
Docker build issue 

### ISSUE THREAD

**Issue by mahadevshindhe** [docker/docker.github.io#14365] opened 2022-03-09 08:32 UTC
https://docs.docker.com/language/java/build-images/

getting docker build issue for above step.

command: docker build --tag java-docker .

PS C:\Users\Downloads\spring-petclinic> docker build --tag java-docker .
[+] Building 14.5s (13/14)
 => [internal] load build definition from Dockerfile                                                                                       0.2s
 => => transferring dockerfile: 232B                                                                                                       0.1s
 => [internal] load .dockerignore                                                                                                          0.1s
 => => transferring context: 34B                                                                                                           0.1s
 => resolve image config for docker.io/docker/dockerfile:1                                                                                 5.9s
 => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:42399d4635eddd7a9b8a24be879d2f9a930d0ed040a61324cfdf59ef1357b3b2            0.0s
 => [internal] load build definition from Dockerfile                                                                                       0.0s
 => [internal] load .dockerignore                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/openjdk:16-alpine3.13                                                                   6.0s
 => [1/6] FROM docker.io/library/openjdk:16-alpine3.13@sha256:49d822f4fa4deb5f9d0201ffeec9f4d113bcb4e7e49bd6bc063d3ba93aacbcae             0.0s
 => [internal] load build context                                                                                                          0.8s
 => => transferring context: 9.47kB                                                                                                        0.8s
 => CACHED [2/6] WORKDIR /app                                                                                                              0.0s
 => CACHED [3/6] COPY .mvn/ .mvn                                                                                                           0.0s
 => CACHED [4/6] COPY mvnw pom.xml ./                                                                                                      0.0s
 => ERROR [5/6] RUN mvnw dependency:go-offline                                                                                             0.8s
------
 > [5/6] RUN mvnw dependency:go-offline:
#13 0.798 /bin/sh: mvnw: not found
------
executor failed running [/bin/sh -c mvnw dependency:go-offline]: exit code: 127
PS C:\Users\Downloads\spring-petclinic>

### Problem location

- I saw a problem at the following URL: <Add URL>

- I couldn't find the information I wanted. I expected to find it near the following URL <Add the URL and briefly describe how we can improve the existing content>

- Other: <Add details that can help us understand the issue>

**Comment by craig-osterhout** [comment] 2022-06-23 21:26
This appears to be a duplicate of https://github.com/docker/docker.github.io/issues/13930
Closing in favor of that issue.

**Closed by craig-osterhout** 2022-06-23 21:26 UTC
