### ISSUE TITLE
404 at /engine/installation/linux/docker-ce/

### ISSUE THREAD

**Issue by Karthik-Y** [docker/docker.github.io#4024] opened 2017-07-29 17:35 UTC
URL: /engine/installation/linux/docker-ce/
URL: https://docs.docker.com/engine/installation/linux/docker-ce/#install-using-the-repository

This link appears broken.

**Comment by joaofnfernandes** [comment] 2017-08-21 19:17
I can't reproduce this, so it's possible that this has been fixed. @Karthik-Y I'm going to close this issue but feel free to comment, if you're still seeing this.

**Closed by joaofnfernandes** 2017-08-21 19:17 UTC

**Comment by Karthik-Y** [comment] 2017-08-25 09:20
@joaofnfernandes It is okay to have this ticket closed and I think this ticket is a duplicate of #4023 which has been fixed and apologies for the confusion. Thanks for looking at it.
