### ISSUE TITLE
Language-specific guides request

### ISSUE THREAD

**Issue by djmarcus1** [docker/docker.github.io#12850] opened 2021-05-15 19:02 UTC
### Problem description

Add guide for C#

### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by thaJeztah** [comment] 2021-12-02 14:25
Thanks for requesting; let me close this as duplicate of https://github.com/docker/docker.github.io/issues/12697

**Closed by thaJeztah** 2021-12-02 14:25 UTC
