### ISSUE TITLE
unable to start container process: exec: "./mvnw dependency:resolve": stat ./mvnw dependency:resolve: no such file or directory

### ISSUE THREAD

**Issue by JTBJ** [docker/docker.github.io#15377] opened 2022-08-12 18:21 UTC
### Problem description
location: Dockerfile
reference: docker documentation (Java section)
documentation url: [https://docs.docker.com/language/java/build-images/](https://github.com/docker/docker.github.io/issues/url)
problem: `RUN ./mvnw dependency:resolve`
error:
```
ERROR [5/6] RUN ["./mvnw dependency:resolve"]                                                                                                                                     0.9s
 > [5/6] RUN ["./mvnw dependency:resolve"]:
#15 0.836 runc run failed: unable to start container process: exec: "./mvnw dependency:resolve": stat ./mvnw dependency:resolve: no such file or directory
executor failed running [./mvnw dependency:resolve]: exit code: 1
```

I'm completing the Java section of the Docker guides. The problem is with a command provided in Dockerfile that I'm using, as specified in the documentation.  When I attempt to run `docker build --tag java-docker .` from the command line, I get the above error. The error corresponds to the **RUN entry in the Dockerfile**.

### Problem location
Location-url: [https://docs.docker.com/language/java/build-images/](https://github.com/docker/docker.github.io/issues/url)
Location-file: Dockerfile
Location-command: RUN
Actual-command:  `./mvnw dependency:resolve`

**Comment by craig-osterhout** [comment] 2022-08-12 19:39
Hi @JTBJ, if you're using Windows, please check/fix the line endings to Unix line endings in the app source files.
It's better to check them all, but if I remember correctly, the problem for me was in the `mvnw` file and the *.java files under `/src`.

If you need more support, please try the Docker Community Slack or Forums.
- https://dockercommunity.slack.com/
- https://forums.docker.com/

**Comment by craig-osterhout** [comment] 2022-08-12 19:51
Closing as this appears to be a duplicate of #13930.

**Closed by craig-osterhout** 2022-08-12 19:51 UTC
Labels: area/get-started
