### ISSUE TITLE
Cannot select documentation version (dropdown is broken)

### ISSUE THREAD

**Issue by akatrevorjay** [docker/docker.github.io#3066] opened 2017-04-26 05:46 UTC
In both Chrome and Firefox:

![out](https://cloud.githubusercontent.com/assets/1312290/25419695/010d53d2-2a09-11e7-800c-b07556e3ff96.gif)

CC @johndmulhausen

**Comment by johndmulhausen** [comment] 2017-04-26 20:31
@allejo If you're out there; I think the CSS changes we made for the hackathon caused this. Z-index is already at 1000 and I couldn't figure it out. Any ideas?

**Comment by allejo** [comment] 2017-04-26 20:54
@johndmulhausen Seems like this was broken in #2804 

https://github.com/docker/docker.github.io/blame/master/_scss/_navigation.scss#L7
https://github.com/docker/docker.github.io/blame/master/_scss/_navigation.scss#L67

Maybe @jsouth could explain the need for `overflow: hidden`?

**Comment by jsouth** [comment] 2017-04-26 21:52
@allejo - This looks like a regression/mistake from my commit #2804 - I will get resolved!  thanks!

**Comment by jsouth** [comment] 2017-05-01 21:51
Overflow issue resolved in this PR:
https://github.com/docker/docker.github.io/pull/3132

http://recordit.co/lATLKXHVVx
http://recordit.co/np2MjR6Yj3

**Comment by johndmulhausen** [comment] 2017-05-03 00:12
Thanks for the fix @jsouth !

**Closed by johndmulhausen** 2017-05-03 00:12 UTC
Labels: area/docsite
