### ISSUE TITLE
404 at /compose/compos

### ISSUE THREAD

**Issue by 1-louis** [docker/docker.github.io#12264] opened 2021-02-05 20:04 UTC
I found a broken link : https://docs.docker.com/compose/compos

**Comment by usha-mandya** [comment] 2021-02-09 11:56
@1-louis Thanks for reporting the broken link. Could you let me know how you arrived at this broken link?

**Comment by craig-osterhout** [comment] 2022-04-26 20:40
@1-louis, thanks for sharing the issue. We are unable to reproduce the issue and are closing it due to insufficient information. If you still encounter the issue, please respond with the requested details.

**Closed by craig-osterhout** 2022-04-26 20:40 UTC
