### ISSUE TITLE
404 at /docker-for-azure/

### ISSUE THREAD

**Issue by rohitpc363** [docker/docker.github.io#11849] opened 2020-12-06 08:33 UTC
I found a broken link : https://docs.docker.com/docker-for-azure/
I arrived on this page through: https://github.com/docker/docker.github.io/issues/11847

**Comment by sudo-bmitch** [comment] 2021-01-19 18:50
This appears to be a duplicate of #11847. Closing here, lets track this in the other issue.

**Closed by sudo-bmitch** 2021-01-19 18:50 UTC
