### ISSUE TITLE
Invalid (partial) script selection

### ISSUE THREAD

**Issue by Kiramuxa** [docker/docker.github.io#14790] opened 2022-05-20 17:21 UTC
File: [engine/install/ubuntu.md](https://docs.docker.com/engine/install/ubuntu/)
![image](https://user-images.githubusercontent.com/16748657/169579716-6c7f8828-1585-4e29-ba7a-db15e0bc1057.png)

The script cannot be selected completely due to incorrect css

**Comment by craig-osterhout** [comment] 2022-05-20 21:17
Thanks for sharing the issue. This seems related to #14788 and appears fixed. I'm unable to reproduce it now. Closing this ticket, but please let us know if the issue still persists.

**Closed by craig-osterhout** 2022-05-20 21:17 UTC
