### ISSUE TITLE
Language-specific guides request for c# and .net

### ISSUE THREAD

**Issue by ziaulhasanhamim** [docker/docker.github.io#13431] opened 2021-08-29 17:20 UTC
There is a good number of c# developers using docker for their apps. Also, asp.net core also getting very popular in microservices. . but there is not Language-specific docker guide for c#. it will be better for new docker users if there is a language-specific guide for c#.

**Comment by thaJeztah** [comment] 2021-12-02 14:32
Thanks for requesting; let me close this as duplicate of https://github.com/docker/docker.github.io/issues/12249 and https://github.com/docker/docker.github.io/issues/12697

**Closed by thaJeztah** 2021-12-02 14:32 UTC
