### ISSUE TITLE
kubernetes

### ISSUE THREAD

**Issue by githubtest007** [docker/docker.github.io#12124] opened 2021-01-19 06:19 UTC
File: [docker-for-mac/index.md](https://docs.docker.com/docker-for-mac/)

**Comment by sudo-bmitch** [comment] 2021-01-19 18:29
It's not clear what the issue is you are encountering. Closing for now. If you are still encountering an issue, please clarify with more details in the comments.

**Closed by sudo-bmitch** 2021-01-19 18:29 UTC
