### ISSUE TITLE
Titles no longer provide permalinks

### ISSUE THREAD

**Issue by Telling** [docker/docker.github.io#2392] opened 2017-03-19 15:48 UTC
### Problem description

For as long as I have been using docker, I've been able to click on a title in any given documentation page to get a permalink to said title. This it seems, is no longer possible. Now I have to click in the tree on the right hand side to get a permalink. I consider this a bug, since I've been able to do this forever - but it might be by design?

### Problem location

I was trying to link someone documentation as I have done so many times, i hit the issue on the [Compose file version 3 reference](https://docs.docker.com/compose/compose-file/) page but it seems to be everywhere.

**Comment by joaofnfernandes** [comment] 2017-03-22 17:35
We've removed the ability to click, on the heading to make the functionality a bit more transparent.
As you scroll the page the url is now updated to include an anchor to that heading.

![example](https://cloud.githubusercontent.com/assets/1525937/24212019/281b85a4-0eeb-11e7-975b-f0229693d989.gif)

I'm going to close this issue since this happened by design, but let us know if you find anything broken with that functionality.

**Closed by joaofnfernandes** 2017-03-22 17:35 UTC
