### ISSUE TITLE
python 2 no longer in alpine repository

### ISSUE THREAD

**Issue by NocensRex** [docker/docker.github.io#13812] opened 2021-11-09 09:05 UTC
File: [get-started/02_our_app.md](https://docs.docker.com/get-started/02_our_app/)

The Dockerfile [here](https://docs.docker.com/get-started/02_our_app/#build-the-apps-container-image) needs to be changed to
```python
# syntax=docker/dockerfile:1
FROM node:12-alpine
RUN apk add --no-cache python3 g++ make
WORKDIR /app
COPY . .
RUN yarn install --production
CMD ["node", "src/index.js"]
```
where on the first RUN command python changed to python3

Reason for this is that python (python 2) is no longer in the alpine repository since alpine version 3.5

**Comment by thaJeztah** [comment] 2021-11-12 16:59
Thanks for reporting; I think this should be fixed by https://github.com/docker/docker.github.io/pull/13826, which is now published on docs.docker.com.

Let me go ahead and close this ticket, but feel free to continue the conversation if the issue is not resolved 👍

**Closed by thaJeztah** 2021-11-12 16:59 UTC
