### ISSUE TITLE
Cannot Unmarshal Object 

### ISSUE THREAD

**Issue by sebster2** [docker/docker.github.io#6095] opened 2018-02-27 15:48 UTC
### Problem description
When I try to start any container, I get this error: 

`ERROR: for drone-server  Cannot start service drone-server: oci runtime error: json: cannot unmarshal object into Go value of type []string`

This happens if I start it manually, or if I try `docker-compose up` 

I tried uninstalling and reinstalling docker and docker-compose. This is on SLES. I made sure that docker and docker-compose were up to date. Let me know if you need any more information from me.

**Comment by joaofnfernandes** [comment] 2018-02-27 18:36
My theory on this is that you've built an image that is missing something so that it can be run with the default Docker or Compose commands.
Try running an image like `docker run nginx:latest` or `docker run wordpress:latest` to see if if your Docker installation is OK. If you're able to run any of those images, the problem is with the image that you're using. Otherwise it might be something related to your Docker installation.

I'm closing this issue since there's nothing for us to improve in the docs.
@sebster2 next time that you're stuck, post on https://forums.docker.com/ instead of filing an issue in the docs repo.

**Closed by joaofnfernandes** 2018-02-27 18:36 UTC
Labels: area/compose
