### ISSUE TITLE
notes-service?

### ISSUE THREAD

**Issue by randytaber** [docker/docker.github.io#11706] opened 2020-11-05 15:25 UTC
File: [get-started/nodejs/develop.md](https://docs.docker.com/get-started/nodejs/develop/)

you reference 'notes-service' from the previous tutorials....but notes-service is never mentioned in the previous tutorials

**Comment by gibbok** [comment] 2020-11-27 11:34
Yes correct, it also does not appear in any search result
https://docs.docker.com/search/?q=%22notes-service%22

**Comment by royas** [comment] 2020-12-14 07:39
It's a duplicate of #11518.

**Comment by craig-osterhout** [comment] 2022-06-13 21:52
Thanks for sharing this issue. As this issue is old, some context was lost when files were moved around in the repo. Based on the duplicate issue in the previous comment, it appears the issue was fixed. If the issue still persists, please let us know.

**Closed by craig-osterhout** 2022-06-13 21:52 UTC
