### ISSUE TITLE
Right-side TOC not fits on <1280, no scrollbar

### ISSUE THREAD

**Issue by mcd-php** [docker/docker.github.io#2758] opened 2017-04-13 07:32 UTC
Right table of contents is cut on resolutions <1280px, and no scroll bar at the bottom, so can't move left TOC out of view. In Ubuntu with non-hiding left application bar (window.innerWidth -> 1215), it's even more grave.

![https___docs docker com_compose_compose-file_-800x600b1280x1024](https://cloud.githubusercontent.com/assets/3469206/24994506/c9d57c84-2033-11e7-95fa-194269ff1f6f.jpg)

Seen at: https://docs.docker.com/compose/compose-file/

**Comment by joaofnfernandes** [comment] 2017-04-13 22:24
Closing as duplicate of #2730

**Closed by joaofnfernandes** 2017-04-13 22:24 UTC
