### ISSUE TITLE
Feedback for: machine/drivers/aws.md

### ISSUE THREAD

**Issue by AstraSerg** [docker/docker.github.io#490] opened 2016-11-08 13:56 UTC
URL: [https://docs.docker.com/machine/drivers/aws.md](https://docs.docker.com/machine/drivers/aws/)

AWS had changed AMI images naming and docker-machine option:

`--amazonec2-ami`

don't work any more.

**Comment by londoncalling** [comment] 2016-11-11 21:54
@nathanleclaire do we have an alternative for this flag, per @AstraSerg 's comment?

**Comment by nathanleclaire** [comment] 2016-11-11 22:54
I'd be curious to know how exactly it's failing.  @AstraSerg can you please post some error output?  I'm assuming it's caused by the transition to longer IDs, but I'm not sure why AWS wouldn't accept them if they were valid 17-character AMI IDs?

**Comment by AstraSerg** [comment] 2016-11-13 18:24
@nathanleclaire Sorry, but I can'y reproduce the error. I believe it was temporary error in AWS. I will check the console cache for detail analyzing tomorrow, if did not clear it.

**Comment by AstraSerg** [comment] 2016-11-14 11:36
Sorry, guys. I cleared the console history and can't give you the error message.

**Comment by nathanleclaire** [comment] 2016-11-14 17:56
OK thanks @AstraSerg -- @londoncalling I'm going to recommend a close, @AstraSerg please keep us posted with more details if you hit the issue again.

**Comment by londoncalling** [comment] 2016-11-14 23:35
@AstraSerg closing per @nathanleclaire 's comments. Keep in touch per this issue, though, per Nathan's suggestions if needed.

**Closed by londoncalling** 2016-11-14 23:35 UTC
