### ISSUE TITLE
Don't forget to ssh to a created VM to start using a 'docker' command

### ISSUE THREAD

**Issue by kirill-oficerov** [docker/docker.github.io#12597] opened 2021-03-30 16:59 UTC
File: [machine/index.md](https://docs.docker.com/machine/)

Now the page says:

> Point the Machine CLI at a running, managed host, and you can run docker commands directly on that host. For example, run docker-machine env default to point to a host called default, follow on-screen instructions to complete env setup, and run docker ps, docker run hello-world, and so forth.

I suggest to add that after following on-screen instructions you need to connect to a docker machine first, by using something like
> docker-machine.exe ssh default
and then you can use 'docker' command. 

Not doing this in Windows 8.1 gives me in cmd:
> 'docker' is not recognized as an internal or external command, operable program or batch file.
and in bash:
> 
bash: docker: command not found

**Comment by craig-osterhout** [comment] 2022-08-02 23:02
Thanks for sharing the issue. Closing as the issue is no longer applicable. Docker Machine is now deprecated.

**Closed by craig-osterhout** 2022-08-02 23:02 UTC
