### ISSUE TITLE
Language-specific guides request for C#

### ISSUE THREAD

**Issue by creatorX64** [docker/docker.github.io#12697] opened 2021-04-18 09:05 UTC
This is a language-specific guides request for C# (specifically for ASP.NET Core platform, just like the Node.js platform).

The current documentation is all-around perfect. My eyes went looking for an ASP.NET Core guide in the docs but couldn't find it. Giving the fact that there are limited (and honestly plain misleading) information on the internet regarding the subject, it would be great if you could add a proper ASP.NET Core guide to the docs.

**Comment by tymik** [comment] 2022-01-19 20:15
Thank you for your request. I will close this one as a duplicate of #12249

**Closed by tymik** 2022-01-19 20:15 UTC
