### ISSUE TITLE
Enter key doesn't print carriage return

### ISSUE THREAD

**Issue by superruzafa** [docker/docker.github.io#3475] opened 2017-06-02 11:49 UTC
### Problem description

When creating a container, return key doesn't print "\r"

```
$ docker run --rm -it ubuntu bash
root@08e17e341a92:/# ↲ 
                     root@08e17e341a92:/# ↲
                                          root@08e17e341a92:/# ↲
                                                               root@08e17e341a92:/#
```

### Project version(s) affected

Docker Edge >= 17.06.0-ce-rc1

### Suggestions for a fix

Could be fixed by manually issuing an `stty sane`.

**Comment by c0s** [comment] 2017-06-07 20:02
Thank you! Was driving me nuts! Damn you Docker ;(

**Comment by joaofnfernandes** [comment] 2017-06-09 16:11
I'm closing this as the issue is being tracked in moby/moby#33489. You can follow updates there.

**Closed by joaofnfernandes** 2017-06-09 16:11 UTC
