### ISSUE TITLE
Additional property {property} is not allowed

### ISSUE THREAD

**Issue by AlexOQ** [docker/docker.github.io#4303] opened 2017-08-21 13:48 UTC
File: [get-started/part3.md](https://docs.docker.com/get-started/part3/), CC @johndmulhausen 
When following the example to the letter, receiving the aforementioned error when running **docker stack deploy** command

Env. details: Latest docker + docker-compose as of this writing, Ubuntu Server 16.04 LTS. Not root, 'sudo' everywhere.

![image](https://user-images.githubusercontent.com/30403857/29522019-81353708-8690-11e7-9e71-34a3c30d27b9.png)

Thanks in advance.

**Comment by joaofnfernandes** [comment] 2017-08-21 17:34
Instead of an image, can you paste here your `getstartedlab` file?
[Check here how to paste code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

**Comment by guk727** [comment] 2017-09-29 03:39
@AlexOQ  You should set an empty line before services and networks like this:
![image](https://user-images.githubusercontent.com/9793258/30999945-c6d04cce-a50a-11e7-991e-045cbddb31c6.png)

**Comment by johndmulhausen** [comment] 2018-01-23 20:55
I think the docs are fine here, so closing this.

**Closed by johndmulhausen** 2018-01-23 20:55 UTC
Labels: area/tutorials, issue/support-request

**Comment by prashant-sinha** [comment] 2018-02-21 11:09
Check indentation. In the original screenshot, `ports` and `networks` property are defined under `deploy`. They should be properties under `web`

**Comment by flyefe** [comment] 2021-12-17 15:31
$ docker compose up
services.mongo-expres Additional property images is not allowed

![image](https://user-images.githubusercontent.com/60510657/146567445-32ce1d78-9ede-4ede-ac68-6c25ed045ab7.png)


version: "20.0"
services:
  mongodb:
    image: mongo
    container_name: monogodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONOGO_INITDB_ROOT_PASSWORD=rootpass
  mongo-expres:
    images: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_AMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_AMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  data: {}

the above code is my docker-compose.yaml file I ran with the docker compose up command. 

what exactly could be wrong? I am on a windows machine

**Comment by dingiso** [comment] 2022-01-06 02:16
> 

change the  string "images" in mongo-express to "image which is located in the line 14

**Comment by dingiso** [comment] 2022-01-06 02:16
> $ docker compose up services.mongo-expres Additional property images is not allowed
> 
> ![image](https://user-images.githubusercontent.com/60510657/146567445-32ce1d78-9ede-4ede-ac68-6c25ed045ab7.png)
> 
> `version: "20.0"` `services:` `mongodb:` `image: mongo` `container_name: monogodb` `ports:` ` - 27017:27017` `volumes:` `- data:/data` `environment:` `- MONGO_INITDB_ROOT_USERNAME=rootuser` `- MONOGO_INITDB_ROOT_PASSWORD=rootpass` `mongo-expres:` ` images: mongo-express` `container_name: mongo-express` ` restart: always` `ports:` `- 8081:8081` ` environment:` ` - ME_CONFIG_MONGODB_AMINUSERNAME=rootuser` ` - ME_CONFIG_MONGODB_AMINPASSWORD=rootpass` ` - ME_CONFIG_MONGODB_SERVER=mongodb` `volumes:` ` data: {}`
> 
> ![image](https://user-images.githubusercontent.com/60510657/146569563-54bffdfd-b1c0-46c9-bc36-eb1c6321ac8c.png)
> 
> the above code is my docker-compose.yaml file I ran with the docker compose up command.
> 
> what exactly could be wrong? I am on a windows machine

change the string "images" in mongo-express to "image which is located in the line 14

**Comment by hayjay** [comment] 2022-12-17 00:13
I faced the issue : `Additional property {property} is not allowed` when running `docker-compose up -d` and what I discovered is that this error happens mostly when your indentation is not properly indented.

For example, In my `docker-compose.yml `file I have:

<img width="588" alt="Screenshot 2022-12-17 at 00 00 15" src="https://user-images.githubusercontent.com/23115829/208210549-1edc3e33-92c3-4ce0-befa-8ad74d8e7cfe.png">

Notice the white space on line 25 after the `${MYSQL_PORT}:` and before the port number `3306`.

That alone was the cause of my problem (I had to remove the white space to make it work). Other similar issues are just indentations like this:

<img width="154" alt="Screenshot 2022-12-17 at 00 03 50" src="https://user-images.githubusercontent.com/23115829/208210765-9a08b8bb-8435-4a7e-a3cb-5d908a556434.png">

On line 2, you will see that I have setup an indentation for services. In this `docker-compose.yml` file, my services are intended to be three `services` namely: `server`, `mysql` and `client` as seen on line 3, 15 and 29 but looking at the above image, I ran into `Additional property client is not allowed` because the indentation on line 29 for the client service shows that the client service is part of the properties of the mysql service which starts from line 15.

To resolve this, I need to find a way to make the `yml` file know that the client should also be a service on its own. This means that I need to remove the whitespace on line 29 and make it align with the indentation of the previous services as seen on line 3(`server`) and 15(`mysql`). The image below shows the final fix:

<img width="135" alt="Screenshot 2022-12-17 at 00 11 06" src="https://user-images.githubusercontent.com/23115829/208211340-c3159276-8c6a-40e0-821f-2caf3145a7f5.png">

**Comment by Beigh-Farooq** [comment] 2022-12-26 17:03
> $ docker compose up services.mongo-expres Additional property images is not allowed
> 
> ![image](https://user-images.githubusercontent.com/60510657/146567445-32ce1d78-9ede-4ede-ac68-6c25ed045ab7.png)
> 
> `version: "20.0"` `services:` `mongodb:` `image: mongo` `container_name: monogodb` `ports:` ` - 27017:27017` `volumes:` `- data:/data` `environment:` `- MONGO_INITDB_ROOT_USERNAME=rootuser` `- MONOGO_INITDB_ROOT_PASSWORD=rootpass` `mongo-expres:` ` images: mongo-express` `container_name: mongo-express` ` restart: always` `ports:` `- 8081:8081` ` environment:` ` - ME_CONFIG_MONGODB_AMINUSERNAME=rootuser` ` - ME_CONFIG_MONGODB_AMINPASSWORD=rootpass` ` - ME_CONFIG_MONGODB_SERVER=mongodb` `volumes:` ` data: {}`
> 
> ![image](https://user-images.githubusercontent.com/60510657/146569563-54bffdfd-b1c0-46c9-bc36-eb1c6321ac8c.png)
> 
> the above code is my docker-compose.yaml file I ran with the docker compose up command.
> 
> what exactly could be wrong? I am on a windows machine

I am facing same issue???????????????????????????
