### ISSUE TITLE
cloudstore plugin is not listed on plugins list

### ISSUE THREAD

**Issue by myaser** [docker/docker.github.io#10106] opened 2020-01-05 16:59 UTC
### Problem description
the cloudstor plugin is not mentioned in the list of volume plugins

### Problem location

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/engine/extend/legacy_plugins/

**Comment by craig-osterhout** [comment] 2022-05-25 22:13
Thanks for sharing this issue. This particular topic is maintained in an upstream repo. If the issue is still applicable, please help create an issue or a PR in the source repo at https://github.com/docker/cli/tree/master/docs/extend
Closing this issue as unable to fix in this repo.

**Closed by craig-osterhout** 2022-05-25 22:13 UTC
Labels: area/Engine
