### ISSUE TITLE
404 at /go/compose-native-build/

### ISSUE THREAD

**Issue by rshurts** [docker/docker.github.io#12140] opened 2021-01-20 15:20 UTC
I found a broken link : https://docs.docker.com/go/compose-native-build/
I arrived on this page through: https://app.shippable.com/

Our CI installs docker compose through Python pip. It installed `docker-compose-1.28.0`. When compose started up the following was output in the logs:

```
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
```

Clicking the link led to a 404 page.

**Comment by thaJeztah** [comment] 2021-01-20 15:35
thanks! looks like a duplicate of https://github.com/docker/docker.github.io/issues/12138 and will be fixed by https://github.com/docker/docker.github.io/pull/11858

**Closed** 2021-01-20 15:46 UTC
