### ISSUE TITLE
Firefox rendering issue with docs header, right-hand side bar

### ISSUE THREAD

**Issue by humphd** [docker/docker.github.io#5749] opened 2018-01-15 21:12 UTC
Looking at the docs, I'm seeing inconsistent rendering between Firefox (57.0.4 on macOS 10.13.2) and Chrome (63.0.3239.132)--the header isn't collapsing and the portion that should be on the right is showing on the left.  Here's Chrome followed by Firefox:

<img width="1336" src="https://user-images.githubusercontent.com/427398/34961758-a6485ede-fa0e-11e7-9ff9-d5e5e43117b9.png">

<img width="1338" src="https://user-images.githubusercontent.com/427398/34961767-ac6a6a14-fa0e-11e7-9569-380fd1315e57.png">

File: [opensource/index.md](https://docs.docker.com/opensource/), CC @johndmulhausen

**Comment by L-Hudson** [comment] 2019-01-02 17:50
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Closed by L-Hudson** 2019-01-02 17:50 UTC
Labels: area/site

**Comment by gah242s** [comment] 2019-02-15 21:38
Yes, this is still a problem.  Looks like there is an html/php tag closing issue.

**Comment by bradstewart** [comment] 2019-10-10 19:40
Still an issue (duplicate of #6060). I did some digging and noticed a few things (I'm on macOS, Firefox 62).

The website does NOT work (exhibits the footer issue):
* In Firefox on 4k external monitor, window width < ~2520px.

The website WORKS:
* In Chrome on any monitor, any window width.
* In Firefox on 1900x1200 external monitor, any window width.
* In Firefox on 4k external monitor, window width > ~2520px.
