### ISSUE TITLE
Docker for AWS IAM permissions: provide step-by-step instructions to configure the AWS CloudFormation Service Role

### ISSUE THREAD

**Issue by lmakarov** [docker/docker.github.io#3406] opened 2017-05-25 18:12 UTC
The instructions on these page are not specific enough. I think I've figured out what needs to be done (an could submit a PR to update the docs), however I'm getting an error from AWS IAM, thus not sure I'm doing it right.

**Steps**
1. Open AWS IAM console
2. Policies > Create Policy > Create Your Own Policy
3. Paste the the policy definition from the docs into Policy Document filed
4. Provide a name and click Create Policy

**Expected results**
The policy is created and I can proceed with the AWS CloudFormation Service Role configuration

**Actual Results**
```
An error occurred: Cannot exceed quota for PolicySize: 5120
```
http://take.ms/ujvdN

File: [docker-for-aws/iam-permissions.md](https://docs.docker.com/docker-for-aws/iam-permissions/), CC @johndmulhausen

**Comment by GarPit** [comment] 2017-06-08 12:46
+1

**Comment by lmakarov** [comment] 2017-06-08 13:44
I finally found the answer to how this should be used in the Docker Cloud documentation here:
https://docs.docker.com/docker-cloud/cloud-swarm/link-aws-swarm/

These two pieces really belong together. Adding a link from https://docs.docker.com/docker-for-aws/iam-permissions/ bask to https://docs.docker.com/docker-cloud/cloud-swarm/link-aws-swarm/  would make it a lot more clear.

**Comment by joaofnfernandes** [comment] 2017-08-22 18:10
Duplicate of #3939

**Closed** 2017-09-08 22:02 UTC
Labels: area/editions
