### ISSUE TITLE
Docker Issue

### ISSUE THREAD

**Issue by Hongjeongmin** [docker/docker.github.io#12068] opened 2021-01-08 17:46 UTC
File: [reference/index.md](https://docs.docker.com/reference/)

**Comment by crydotsnake** [comment] 2021-01-09 23:06
Please provide some more informations about the issue...

**Comment by sudo-bmitch** [comment] 2021-01-19 18:48
It's not clear what the issue is you are encountering. Closing for now. If you are still encountering an issue, please clarify with more details in the comments.

**Closed by sudo-bmitch** 2021-01-19 18:48 UTC
