### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by BoltBolten** [docker/docker.github.io#11992] opened 2020-12-27 08:08 UTC
File: [search.md](https://docs.docker.com/search/)

**Comment by thaJeztah** [comment] 2021-01-05 13:46
Could you describe what issue you're seeing?

**Comment by sudo-bmitch** [comment] 2021-01-19 18:51
It's not clear what the issue is you are encountering. Closing for now. If you are still encountering an issue, please clarify with more details in the comments.

**Closed by sudo-bmitch** 2021-01-19 18:51 UTC
