### ISSUE TITLE
Docker.raw diskspace usage

### ISSUE THREAD

**Issue by hjjvandam** [docker/docker.github.io#9895] opened 2019-11-17 04:43 UTC
File: [docker-for-mac/faqs.md](https://docs.docker.com/docker-for-mac/faqs/)

Following on from #7723 I still think that Docker.raw is rather large. I have a Docker setup with two images in it, one of 4 GB and one of 1.5 GB but the Docker.raw file is still 13 GB in size. Admittedly much smaller than the maximum file size of 64 GB but still the size is twice the amount of data the file is supposed to hold. Why is this file so big?

The commands I used to verify this:
```
% docker images
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
chimbuko/run_nwchem   latest              92304859dc15        12 days ago         4.04GB
mpqc4-dev             latest              8d66e7b45b18        2 years ago         1.31GB
% ls -kslh Docker.raw 
13069440 -rw-r--r--  1 vandam  staff    64G Nov 16 23:28 Docker.raw
```

**Comment by filipre** [comment] 2020-03-21 17:49
This is a duplicate of https://github.com/docker/for-mac/issues/2297. I solved your issue by going into `Preferences > Disk` and setting the disk value to the minimum (16GB). The discussion about it should take place there though.

**Comment by aevesdocker** [comment] 2022-04-13 10:28
Closing issue as it refers to old docs that have since been moved/deprecated/refreshed.

**Closed by aevesdocker** 2022-04-13 10:28 UTC
Labels: area/Desktop
