### ISSUE TITLE
Inconsistent of plugin config docs

### ISSUE THREAD

**Issue by ad-m** [docker/docker.github.io#9413] opened 2019-09-10 01:48 UTC
File: [engine/extend/config.md](https://docs.docker.com/engine/extend/config/)
The document within the "env" field is internally inconsistent.

There are three fields listed in the reference documentation for ```env``` property: ```name```, ```description``` and ```value```. Meanwhile, the example provided also contains ```Settable``` field.

The letter case of fields such as ```env``` is also inconsistent with example.

**Comment by craig-osterhout** [comment] 2022-05-25 22:19
Thanks for sharing this issue. This particular topic is maintained in an upstream repo. If the issue is still applicable, please help create an issue or a PR in the source repo at https://github.com/docker/cli/tree/master/docs/extend
Closing this issue as unable to fix in this repo.

**Closed by craig-osterhout** 2022-05-25 22:19 UTC
Labels: area/Engine
