### ISSUE TITLE
docs for Php frameworks

### ISSUE THREAD

**Issue by riettotek** [docker/docker.github.io#14579] opened 2022-04-20 12:33 UTC
### It's a demand for inserting a section about a PHP framework within [Language-specific getting started][1] guides
It's only a suggestions.\
For example, you could set up a section for...
### ...LARAVEL!
Thank u!

[1]: https://docs.docker.com/language/

**Comment by craig-osterhout** [comment] 2022-05-18 20:17
Thanks for requesting. Closing as a duplicate of #12719

**Closed by craig-osterhout** 2022-05-18 20:17 UTC
Labels: kind/enhancement, area/Samples
