### ISSUE TITLE
Feedback for: engine/reference/commandline/service_create.md

### ISSUE THREAD

**Issue by Darkheir** [docker/docker.github.io#2018] opened 2017-02-28 11:50 UTC
File: [engine/reference/commandline/service_create.md](https://docs.docker.com/engine/reference/commandline/service_create/), CC: @mstanleyjones 

There is no information on the website about constraints that may be applied to services and all the docs show this page as reference.

**Comment by kiwi-dejero** [comment] 2017-02-28 15:46
I had to look at an old commit for this info

**Comment by Darkheir** [comment] 2017-02-28 15:58
It seems that everything has been removed in the following commit: mstanleyjones@980f3cc83a4569237e34ae92f97773f58adac4f6

I think it would be a good idea to add it again and browsing quickly, this is not the only page that seems affected

**Comment by joaofnfernandes** [comment] 2017-02-28 20:08
@mstanleyjones this seems to be introduced on #1829 to avoid maintaining duplicate information in two repos. Do what you what's the status on the docker/docker side, so that we can regenerate all these files with all the information they had before?

@Darkheir, @kiwi-dejero in the mean time you can use https://github.com/docker/docker/tree/master/docs/reference/

**Comment by joaofnfernandes** [comment] 2017-03-01 17:13
I'm closing this issue as a duplicate of #1981. You can follow any updates there.

**Closed by joaofnfernandes** 2017-03-01 17:13 UTC
