### ISSUE TITLE
Feedback for: docker-cloud/builds/image-scan.md

### ISSUE THREAD

**Issue by khatkar** [docker/docker.github.io#1433] opened 2017-01-30 17:22 UTC
File: [docker-cloud/builds/image-scan.md](https://docs.docker.com/docker-cloud/builds/image-scan/)

After publishing two different tags for my docker, one was successfully scanned while the image scan for the other failed with message 'Could not complete image scan'. The FAQ webpage does not talk about this issue.

**Comment by toli** [comment] 2017-01-30 18:24
@khatkar - the scan may have failed for a number of various reasons. What's your repo? `namespace:reponame` so that I can search the logs and view it.

**Comment by khatkar** [comment] 2017-01-30 18:37
@toli It is a private repo. Can you tell me where to look for the logs?

**Comment by toli** [comment] 2017-01-30 18:59
The logs are on `docker side` and not exposed to the outside users. 
You can go through support to have them figure out the issue. 
Or you can push the failed tag again and hopefully it'll go through, we fixed a number of issues over the weekend.

**Comment by khatkar** [comment] 2017-01-30 19:07
I will push the image again. Will update this post once it finishes scanning.

**Comment by sanscontext** [comment] 2017-01-30 22:12
@toli, thanks for chiming in. @khatkar we've determined that scans still run on Cloud when you're using multi-tag, so this is likely an issue specific to your configuration. This repo is for docs bugs specifically and is not a support forum, so I'm going to close this issue for now. Please contact support@ and they can help you troubleshoot. If you figure out what's going on and it's still something that needs to be included in the doc, feel free to reopen the issue once you have more details.

**Closed by sanscontext** 2017-01-30 22:12 UTC

**Comment by khatkar** [comment] 2017-01-30 22:23
@sanscontext Thanks. I did not intended to resolve issue through this git post. I just want to see some FAQ of image scan failures. If this is something that docker doesn't do often I can understand.

**Comment by sanscontext** [comment] 2017-01-31 00:38
@khatkar Thanks. It's impossible for us (the docs team) to know all of the failure modes across all users, and to judge if the problem is on our side or your side. Once you've worked with support you can tell us how to better address your needs.
