### ISSUE TITLE
Tons of broken links in Registry documentation

### ISSUE THREAD

**Issue by shakefu** [docker/docker.github.io#1948] opened 2017-02-23 19:34 UTC
### Problem description

Almost every single page links to `configuration.md` which no longer exists. Other pages clearly have been moved without updating links.

### Problem location

- https://github.com/docker/docker.github.io/blob/master/registry/recipes/mirror.md - Under configuring the cache
- https://github.com/docker/docker.github.io/blob/master/registry/deploying.md - Under storage alternatives, Let's Encrypt, restricting access alternatives, next
- Will add more to the ticket as found

### Project version(s) affected

GitHub `master`.

### Suggestions for a fix

Go through and audit all the links and fix them to point at the correct documentation.

**Comment by joaofnfernandes** [comment] 2017-02-23 21:59
@shakefu thanks for reporting this. Some documentation pages are managed in other repositories, so at build time we checkout this repository and a few others, to generate what you see at docs.docker.com.

You can see which doc [pages are managed in other repos here](https://github.com/docker/docker.github.io/blob/master/_data/not_edited_here.yaml).

This approach has the benefit of having specs and docs that can be generated from the source being managed side by side with the code. Unfortunatelly it also has the side effect of having links in the source documentation that point to an article that will only exist at build time.

Since this happens by design, I'm closing this issue, but feel free to create new issues if you find broken links at docs.docker.com.

**Closed by joaofnfernandes** 2017-02-23 21:59 UTC
