### ISSUE TITLE
Autocompletion script for docker-compose not found since the move to GoLang

### ISSUE THREAD

**Issue by SirMorfield** [docker/docker.github.io#14692] opened 2022-05-08 18:32 UTC
File: [compose/completion.md](https://docs.docker.com/compose/completion/)

The link to the `https://raw.githubusercontent.com/docker/compose/v2.5.0/contrib/completion/bash/docker-compose` gives a 404. The rework in Go either moved or deleted the file.
I could not find where it's located right now

**Comment by SirMorfield** [comment] 2022-05-08 18:36
And also the links
`https://raw.githubusercontent.com/docker/compose/v2.5.0/contrib/completion/bash/docker-compose`
`https://raw.githubusercontent.com/docker/compose/v2.5.0/contrib/completion/zsh/_docker-compose `
give 404

**Comment by Mahoney** [comment] 2022-05-11 13:52
I understand [this comment](https://github.com/docker/compose/issues/8550#issuecomment-1119385949) to be saying that the problem is a documentation one - the link should not be in the documentation because there is no bash completion at present for v2 (the rework of docker compose in Go).

Completion will be added when https://github.com/docker/cli/pull/3429 is merged and released.

**Closed** 2022-05-18 10:29 UTC
