### ISSUE TITLE
usingdocker.md does not work on Windows

### ISSUE THREAD

**Issue by rillig** [docker/docker.github.io#385] opened 2016-10-29 04:14 UTC
URL: https://docs.docker.com/engine/tutorials/usingdocker/

### Problem description

When following the instructions in `usingdocker.md`, I get a _Connection refused_ error.

To reproduce:
- Start with a Windows 10 host, having VirtualBox 5.0.24 installed
- Install Docker Tools (does not mention that it requires a reboot)
- Follow the instructions in `usingdocker.md`
- At `you can now browse`, get a connection refused error

I tried to connect to these ports:
- localhost:5000
- localhost:32768
- 192.168.99.100:32768

None of them worked. Also, `docker-machine ip` always returned `Host does not exist`, no matter what I passed as arguments. After rebooting Windows, connecting to `192.168.99.100:32768` worked.
Since `docker-machine ip` still did not work, the only hint for the IP address came from the welcome screen.
### Suggestions for a fix
- Mention that a reboot may be necessary
- Make `docker-machine ip` work

**Comment by johndmulhausen** [comment] 2016-11-11 21:44
@londoncalling Is this something you can take a look at with your Windows machine? :)

**Comment by londoncalling** [comment] 2016-11-15 02:19
@rillig did `localhost:32768` work for you also? I can add a mention of a reboot required in the docs, for now. 

@johndmulhausen I can't test this on my Windows box with Toolbox and Oracle VB, only with Docker for Windows (which works as documented). Re-installing Toolbox at this point would be a little disruptive and maybe not worth it.

@nathanleclaire, @ManoMarks, @friism Any thoughts on this? Do you have a Windows box set up w/Toolbox and VB to test?

**Comment by ManoMarks** [comment] 2016-11-15 08:28
I don't have a windows box set-up to test with only Toolbox on it.

**Comment by londoncalling** [comment] 2017-03-09 20:11
@rillig for Windows 10, you can use Docker for Windows, which will solve these issues easily.

With regard to using Windows 10 with Toolbox, I could not reproduce the issue.

Closing this, please re-open if you continue to have problems with Docker for Windows.

**Closed by londoncalling** 2017-03-09 20:11 UTC
