### ISSUE TITLE
Language-specific guides request

### ISSUE THREAD

**Issue by PHPStormbringer** [docker/docker.github.io#13762] opened 2021-11-01 13:23 UTC
### Problem description

I am completely new to Docker, and would like a setup guide for PHP

**Comment by Gavinaa123aah** [comment] 2021-11-05 18:48
hope to support more languages

**Comment by thaJeztah** [comment] 2021-12-02 14:39
Thanks for requesting; let me close this as duplicate of https://github.com/docker/docker.github.io/issues/12719

**Closed by thaJeztah** 2021-12-02 14:39 UTC
