### ISSUE TITLE
Docker documentation has a hole/is broken

### ISSUE THREAD

**Issue by Atralb** [docker/docker.github.io#11860] opened 2020-12-08 20:09 UTC
The content of this page https://docs.docker.com/get-started/nodejs/develop/ does not follow the previous content as the documentation implies:

>Work through the steps to build an image and run it as a containerized application in [Run your image as a container](https://docs.docker.com/get-started/nodejs/run-containers/).

This page in the quote deals with a custom image called `node-docker` (we create a dockerfile, build the image, and run a container from it), while the one I'm talking about deals with a project called "notes-service", and talks about things that were never mentioned before:

>If you remember from Part I of this series, we had to start the Mongo container manually and connect it to the same network that our notes-service is running on. 

I followed all the previous pages in the natural order of the documentation, and they never even use a Mongo container, nor do they feature container network configuration.

There's also this line:

>Open the notes-service in your IDE or text editor

while the only directory we created before was `node-docker` ([here](https://docs.docker.com/get-started/nodejs/build-images/))

The page still mentions `node-docker` so they surely are meant to be together, but there clearly is a page missing. I'm fairly confident there's a mistake here. 

While this gets worked out, do you know where I can find "Part I of this series" ?

Thanks in advance.

**Comment by royas** [comment] 2020-12-14 07:40
It's a duplicate of #11518.

**Comment by craig-osterhout** [comment] 2022-06-13 22:47
Thanks for sharing the issue. This appears fixed in https://github.com/docker/docker.github.io/pull/11770
If the issue still persists, please let us know.

**Closed by craig-osterhout** 2022-06-13 22:47 UTC
