### ISSUE TITLE
404 at /docker-for-aws/

### ISSUE THREAD

**Issue by Dizzydaizys** [docker/docker.github.io#12111] opened 2021-01-16 01:05 UTC
I found a broken link : https://docs.docker.com/docker-for-aws/
I arrived on this page through: https://github.com/docker/docker.github.io/issues/12110

**Comment by sudo-bmitch** [comment] 2021-01-19 18:34
This appears to be a duplicate of #12110 . Closing here, lets track this in the other issue.

**Closed by sudo-bmitch** 2021-01-19 18:34 UTC
