### ISSUE TITLE
404 at /compose/production/swarm.md

### ISSUE THREAD

**Issue by szvictdo** [docker/docker.github.io#11611] opened 2020-10-22 21:43 UTC
I found a broken link : https://docs.docker.com/compose/production/swarm.md

**Comment by jerae-duffin** [comment] 2021-05-20 19:42
@szvictdo 
Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

**Comment by craig-osterhout** [comment] 2022-04-26 21:08
@szvictdo, thanks for sharing the issue. We are unable to reproduce the issue and are closing it due to insufficient information. If you still encounter the issue, please respond with the requested details.

**Closed by craig-osterhout** 2022-04-26 21:08 UTC
