### ISSUE TITLE
404 at /desktop/mac/release-notes/undefined

### ISSUE THREAD

**Issue by hbyangjianquan** [docker/docker.github.io#13443] opened 2021-09-01 02:25 UTC
I found a broken link : https://docs.docker.com/desktop/mac/release-notes/undefined
I arrived on this page through: https://docs.docker.com/desktop/mac/release-notes/

**Comment by thaJeztah** [comment] 2021-12-02 14:12
Looks the same as https://github.com/docker/docker.github.io/issues/13553 (and some other reports), but so far we haven't been able to find the cause for these broken links (it _may_ be a JavaScript issue)

Do you know what link you clicked on that page? What browser (and version) are you using, and do you have any browser extensions installed?

Let me close this ticket in favor of #13553, but if you're able to provide more details that could help us find the problem, feel free to comment on that ticket!

**Closed by thaJeztah** 2021-12-02 14:12 UTC
Labels: status/need-more-info
