### ISSUE TITLE
Better GusterFS Plugin

### ISSUE THREAD

**Issue by fossler** [docker/docker.github.io#8906] opened 2019-06-06 21:24 UTC
File: [engine/extend/legacy_plugins.md](https://docs.docker.com/engine/extend/legacy_plugins/)

This GlsterFS Plugin ist maintained:
https://github.com/trajano/docker-volume-plugins/tree/master/glusterfs-volume-plugin

**Comment by marcelo-ochoa** [comment] 2021-03-16 19:49
Updated version of GlusterFS Plugin is at: [docker-volume-plugins](https://github.com/marcelo-ochoa/docker-volume-plugins)
Including S3 Volume Plugin.
Docker Hub Download:
- [GlusterFs](https://hub.docker.com/repository/docker/mochoa/glusterfs-volume-plugin)
- [S3 FS](https://hub.docker.com/repository/docker/mochoa/s3fs-volume-plugin)
ARM Versions soon.

**Comment by craig-osterhout** [comment] 2022-05-25 22:24
Thanks for sharing this issue. This particular topic is maintained in an upstream repo. If the issue is still applicable, please help create an issue or a PR in the source repo at https://github.com/docker/cli/tree/master/docs/extend
Closing this issue as unable to fix in this repo.

**Closed by craig-osterhout** 2022-05-25 22:24 UTC
Labels: area/Engine
