### ISSUE TITLE
"Notes:

### ISSUE THREAD

**Issue by sarahpark** [docker/docker.github.io#3408] opened 2017-05-25 21:02 UTC
File: [engine/installation/linux/ubuntu.md](https://docs.docker.com/engine/installation/linux/ubuntu/), CC @mstanleyjones

**Comment by JimGalasyn** [comment] 2017-05-25 23:48
Dupe of #3409 .

**Closed by JimGalasyn** 2017-05-25 23:48 UTC

**Comment by sarahpark** [comment] 2017-05-25 23:59
Oh whoops, not sure how this happened 😅
