### ISSUE TITLE
Language-specific guides request

### ISSUE THREAD

**Issue by wyattbiker** [docker/docker.github.io#13173] opened 2021-07-12 22:08 UTC
### Problem description
Please create a guide for PHP.  Why is there no language guide for PHP? It happens to be one of the top web development tools in the world.

Thanks!

**Comment by rubersonramon7** [comment] 2021-08-05 16:29
Please create a guide for PHP.

**Comment by navidanwar** [comment] 2021-08-06 04:20
Please create a guide for both languages PHP and .NET as well.

**Comment by outspokenjoules** [comment] 2021-08-11 18:20
Yes, PHP please! Bonus points if it includes the pdo_mysql extension.

**Comment by aadil96** [comment] 2021-09-12 11:56
+1

**Comment by thaJeztah** [comment] 2021-12-02 14:30
Thanks for requesting; let me close this as duplicate of https://github.com/docker/docker.github.io/issues/12719 and https://github.com/docker/docker.github.io/issues/12249

**Closed by thaJeztah** 2021-12-02 14:30 UTC
