### ISSUE TITLE
404 at /article-img/architecture.svg

### ISSUE THREAD

**Issue by NazariiPrubniak** [docker/docker.github.io#11820] opened 2020-12-01 20:59 UTC
I found a broken link : https://docs.docker.com/article-img/architecture.svg

**Comment by jerae-duffin** [comment] 2021-05-11 14:29
Hi @NazariiPrubniak can you provide more details on how you arrived to this link?

**Comment by craig-osterhout** [comment] 2022-04-26 20:50
@NazariiPrubniak, thanks for sharing the issue. We are unable to reproduce the issue and are closing it due to insufficient information. If you still encounter the issue, please respond with the requested details.

**Closed by craig-osterhout** 2022-04-26 20:50 UTC
