### ISSUE TITLE
Some more info in docker image inspect command documentation

### ISSUE THREAD

**Issue by ThomasSchoenbeck** [docker/docker.github.io#7599] opened 2018-10-31 12:06 UTC
File: [engine/reference/commandline/image_inspect.md](https://docs.docker.com/engine/reference/commandline/image_inspect/)

it would be nice to get some more information of what could be expected as a result from this command. the description only tells you that it exists and how you can update the format. it does not tell you which type of information you will receive and what format choices you have.

**Comment by craig-osterhout** [comment] 2022-05-26 20:27
Thanks for sharing the issue. This particular content is from an upstream repo and can't be fixed in the docker.github.io repo. If the issue is still applicable, please help create an issue/discussion in the source repo at https://github.com/docker/cli/tree/master/docs/reference/commandline

**Closed by craig-osterhout** 2022-05-26 20:27 UTC
Labels: area/Engine
