### ISSUE TITLE
The downloaded docker installer doesn't have an extension, have to add '.dmg' mannually

### ISSUE THREAD

**Issue by SiboYang** [docker/docker.github.io#15196] opened 2022-07-23 21:09 UTC
File: [desktop/install/mac-install.md](https://docs.docker.com/desktop/install/mac-install/)

the downloaded installer doesn't have a "dmg" extension
OS: macOS 12.3
Mac with Apple silicon

**Comment by usha-mandya** [comment] 2022-07-25 09:29
@SiboYang Thanks for flagging this. Could you let us know if you download Docker Desktop for Mac with Intel or Mac with Apple silicon?

**Comment by usha-mandya** [comment] 2022-07-26 15:49
@SiboYang Thanks for confirming. The download has a `.dmg` extension when I tried a few minutes ago. Could you retry and see if you still have this issue?

**Comment by thaJeztah** [comment] 2022-07-27 19:22
Thanks for reporting; this looks to be the same issue as https://github.com/docker/for-mac/issues/6411, and is caused by a bug in Firefox 102, that should be fixed in newer versions of Firefox; https://github.com/docker/for-mac/issues/6411#issuecomment-1189574545


I'm closing this ticket, as this is not a bug on our servers, but feel free to continue the conversation

**Closed by thaJeztah** 2022-07-27 19:22 UTC
Labels: area/Desktop
