### ISSUE TITLE
404 at /machine/img/provision-use-case.png

### ISSUE THREAD

**Issue by OsvaldoRino** [docker/docker.github.io#13899] opened 2021-11-27 04:08 UTC
I found a broken link : https://docs.docker.com/machine/img/provision-use-case.png
I arrived on this page through: https://github.com/docker/docker.github.io/issues/13897

**Comment by thaJeztah** [comment] 2021-12-02 14:17
duplicate of https://github.com/docker/docker.github.io/issues/13897

**Closed by thaJeztah** 2021-12-02 14:17 UTC
