### ISSUE TITLE
Remind to add port 6443 to firewall rules

### ISSUE THREAD

**Issue by yongshin** [docker/docker.github.io#6663] opened 2018-05-08 22:08 UTC
File: [ee/ucp/admin/install/upgrade.md](https://docs.docker.com/ee/ucp/admin/install/upgrade/)

After upgrading from UCP 2.2.x to UCP 3.x its important to open up port 6443 to talk to Kubernetes nodes via kubectl, otherwise your kubectl commands via client bundle will not work.

**Comment by joaofnfernandes** [comment] 2018-05-08 23:38
For context, we had that information. The problem is that there are a ton more things that you should do, other than opening port 6443:
* There are other ports that you need to have open
* You need to allow IP protocol 4
* Minimum memory requirements increased
* And a couple of other details

If we added all that information to the upgrade page, we would be basically replicating the information that already exists in the system requirements. So the first step before upgrading, is making sure your system complies with the system requirement of the new version.

And of course, you shouldn't upgrade before making sure you have a recent backup, just in case things go sideways during the upgrade.

![2018-05-08_16-36-00](https://user-images.githubusercontent.com/1525937/39788194-250dd410-52de-11e8-8e00-08bb66c31150.png)

I don't think we should add that specific port to the upgrade page, so I'm closing this issue.
@yongshin let me know if you disagree.

**Closed** 2018-05-08 23:38 UTC
