### ISSUE TITLE
Language-specific guides request

### ISSUE THREAD

**Issue by ravidolas** [docker/docker.github.io#13938] opened 2021-12-06 03:13 UTC
### Currently not able to find the guide and details for containerizing C++ Application.

- Not able to find the documentation for C++ language 

- I couldn't find the information I wanted. I expected to find it near the following URL <Add the URL and briefly describe how we can improve the existing content>

- Other: <Add details that can help us understand the issue>

**Comment by tymik** [comment] 2022-01-19 21:57
Thank you for you report. I am closing it as a duplicate of #12324

**Closed by tymik** 2022-01-19 21:57 UTC
