### ISSUE TITLE
Docker for Windows error: docker-machine scp doesn't work

### ISSUE THREAD

**Issue by aeszalacinski** [docker/docker.github.io#3670] opened 2017-06-20 19:46 UTC
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/), CC @johndmulhausen 

Reference https://forums.docker.com/t/you-must-have-a-copy-of-the-scp-binary-locally-to-use-the-scp-feature/29260/7

**Comment by NonCreature0714** [comment] 2017-06-28 18:22
I have this same issue. "[Getting Started, Part 4: Swarms](https://docs.docker.com/get-started/part4/#deploy-your-app-on-a-cluster)" uses this command. There isn't much of a workaround in Windows. I also opened up an issue [on docker-machine's issues](https://github.com/docker/machine/issues/4155).

**Comment by mstanleyjones** [comment] 2017-07-03 23:52
Duplicate of #3648

**Closed by mstanleyjones** 2017-07-03 23:52 UTC
