### ISSUE TITLE
1

### ISSUE THREAD

**Issue by 212KeyserSoJay** [docker/docker.github.io#12091] opened 2021-01-13 15:47 UTC
File: [get-started/nodejs/run-containers.md](https://docs.docker.com/get-started/nodejs/run-containers/)

**Comment by sudo-bmitch** [comment] 2021-01-19 18:37
It's not clear what the issue is you are encountering. Closing for now. If you are still encountering an issue, please clarify with more details in the comments.

**Closed by sudo-bmitch** 2021-01-19 18:37 UTC
