### ISSUE TITLE
Debugging plugins does not work as described anymore

### ISSUE THREAD

**Issue by djmaze** [docker/docker.github.io#12474] opened 2021-03-11 08:33 UTC
File: [engine/extend/index.md](https://docs.docker.com/engine/extend/)

On my 19.03.8 installation, the directory `/var/run/docker/plugins/runtime-root/moby-plugins/` is empty while `/var/run/docker/plugins/runtime-root/plugins.moby/` contains the plugin states.

But just adjusting the path in the runc command is not enough. The internal data structures seem to have changed:

```bash
$ docker-runc --root /var/run/docker/plugins/runtime-root/plugins.moby list
load container 04172e87ffdac4dd488a00b42b2e37608d744c24000155a3d25a71d4d1e3a7bc: json: cannot unmarshal number into Go struct field State.init_process_start of type string
load container dc77a73da700d8841cc7654291e3f56683b757a9deb998684b6ca8e445cced16: json: cannot unmarshal number into Go struct field State.init_process_start of type string
load container ec5c481438d0be1a459b450e14f0240398676c97d5c75eed60ff28cf52ed58d1: json: cannot unmarshal number into Go struct field State.init_process_start of type string
ID          PID         STATUS      BUNDLE      CREATED
```

**Comment by craig-osterhout** [comment] 2022-05-25 21:55
Thanks for sharing the issue. This particular topic is maintained in an upstream repo. If the issue is still applicable, please help create an issue or a PR in the source repo at https://github.com/docker/cli/tree/master/docs/extend
Closing this issue.

**Closed by craig-osterhout** 2022-05-25 21:55 UTC
