### ISSUE TITLE
S3 Storage Configuration Changes Between DTR 2.2 and 2.3 

### ISSUE THREAD

**Issue by lmuchnick** [docker/docker.github.io#5659] opened 2018-01-03 16:13 UTC
File: [datacenter/dtr/2.3/guides/admin/upgrade.md](https://docs.docker.com/datacenter/dtr/2.3/guides/admin/upgrade/), CC @joaofnfernandes 

Customer, PrismHR, upgraded from DTR 2.2.x to 2.3.x and could no longer push images.  After troubleshooting it was identified that there are additional configuration steps required for DTR 2.3 that were not required in DTR 2.2.  Customer has requested that we add a note in the release notes and upgrade guide for DTR 2.3 to identify this change.

DTR 2.3 additional configuration steps:

`Configure your clients`

`If you’re using a TLS certificate in your storage backend that’s not globally trusted, you’ll have to configure all Docker Engines that push or pull from DTR to trust that certificate. When you push or pull an image DTR redirects the requests to the storage backend, so if clients don’t trust the TLS certificates of both DTR and the storage backend, they won’t be able to push or pull images. Learn how to configure the Docker client.`

`And if you’ve configured DTR to skip TLS verification, you also need to configure all Docker Engines that push or pull from DTR to skip TLS verification. You do this by adding DTR to the list of insecure registries when starting Docker.`

**Comment by joaofnfernandes** [comment] 2018-01-04 18:42
Closing as duplicate of #5657

**Closed by joaofnfernandes** 2018-01-04 18:42 UTC
Labels: area/dtr
