### ISSUE TITLE
404 at /docker-for-aws/

### ISSUE THREAD

**Issue by ajayramesh23** [docker/docker.github.io#4027] opened 2017-07-29 18:49 UTC
URL: https://docs.docker.com/docker-for-aws/
 - 404 error

![image](https://user-images.githubusercontent.com/2877819/28747464-a39e6596-7464-11e7-9507-7dfe81d64406.png)

**Comment by hairyhenderson** [comment] 2017-07-31 15:49
Dupe of #4026 😉

**Comment by mstanleyjones** [comment] 2017-08-18 20:20
This is no longer happening.

**Closed by mstanleyjones** 2017-08-18 20:20 UTC
