### ISSUE TITLE
The --filter name=xxxx option should say that a full match is not required.

### ISSUE THREAD

**Issue by jeffstearns** [docker/docker.github.io#7533] opened 2018-10-18 02:53 UTC
File: [engine/reference/commandline/ps.md](https://docs.docker.com/engine/reference/commandline/ps/)

The --filter name=xxxx option says only
`name | Container’s name`

The explanation should be clearer, saying that a full match is not required.  This option matches all containers whose name _contains xxxx as a substring_.

Furthermore, I suspect that there's some secret regular expression  processing here; a definitive statement would help.

**Comment by MADBOYJAY1** [comment] 2018-10-23 00:47
Mate I a noon here and to be honest I don't fucking know what I'm doing doing either I'm on a download apk website or to he'll with it I give up

**Comment by craig-osterhout** [comment] 2022-05-26 19:27
Thanks for sharing this issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue/discussion in the source repo at https://github.com/docker/cli/tree/master/docs/reference/commandline 
Closing this as unable to fix in this repo.

**Closed by craig-osterhout** 2022-05-26 19:27 UTC
Labels: area/Engine
