### ISSUE TITLE
docker system prune does not support "--filter until=..."

### ISSUE THREAD

**Issue by islandsvinur** [docker/docker.github.io#7730] opened 2018-11-20 15:27 UTC
According to [edge/engine/reference/commandline/system_prune.md](https://docs.docker.com/edge/engine/reference/commandline/system_prune/), it should be possible to provide an 'until' filter to `docker system prune`. However, with Docker daemon 18.09.0 and fresh `docker:latest` I get:

```
$ docker system prune --force --filter "until=168h"
Error response from daemon: failed to prune build cache: Invalid filter 'until'
$ docker system prune --force --filter 168h
invalid argument "168h" for "--filter" flag: bad format of filter (expected name=value)
```

**Comment by craig-osterhout** [comment] 2022-05-26 17:10
Thanks for sharing this issue. This particular content is maintained in an upstream repo. Since this issue is dated, I'm not sure if it is still applicable. If the issue is still applicable, please help create an issue or PR in the source repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
Closing this as unable to fix in this repo.

**Closed by craig-osterhout** 2022-05-26 17:10 UTC
