### ISSUE TITLE
Language-specific guides request

### ISSUE THREAD

**Issue by TestWordmail** [docker/docker.github.io#13714] opened 2021-10-19 02:57 UTC
### Problem description

I Couldn't find how to upload C and C++ programs to docker.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/language/

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/language/c

### Suggestions for a fix

Please add a page on how to use docker with C and C++. I mainly develop in C and love docker. Just wanted to publish a C app to docker.

**Comment by thaJeztah** [comment] 2021-12-02 14:41
Thanks for requesting; let me close this as duplicate of https://github.com/docker/docker.github.io/issues/12324

**Closed by thaJeztah** 2021-12-02 14:41 UTC
