### ISSUE TITLE
Language-specific guides request

### ISSUE THREAD

**Issue by htrellez** [docker/docker.github.io#13338] opened 2021-08-12 12:50 UTC
### Problem location

- I saw a problem on the following URL: https://docs.docker.com/language/?utm_source=docker&utm_medium=nurture&utm_campaign=21-07nurtureonboarding1&mkt_tok=NzkwLVNTQi0zNzUAAAF-2TmRTg0YsjwYJfe5fJD-bytCltsMuRC7pnWFkg_OyjHUt4WpLcoUozL6Z9yOgf5grKxfQtV5zZ7Fxz2LkZmMHOJ6I0GwjQcNqm1kZm_p

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/language/?utm_source=docker&utm_medium=nurture&utm_campaign=21-07nurtureonboarding1&mkt_tok=NzkwLVNTQi0zNzUAAAF-2TmRTg0YsjwYJfe5fJD-bytCltsMuRC7pnWFkg_OyjHUt4WpLcoUozL6Z9yOgf5grKxfQtV5zZ7Fxz2LkZmMHOJ6I0GwjQcNqm1kZm_p

- Other: Currently you don't have information about of Net Core.

**Comment by thaJeztah** [comment] 2021-12-02 14:34
Thanks for requesting; let me close this as duplicate of https://github.com/docker/docker.github.io/issues/12249 and https://github.com/docker/docker.github.io/issues/12697

**Closed by thaJeztah** 2021-12-02 14:34 UTC
