### ISSUE TITLE
dockerd-rootless-setuptool.sh is trying to use the docker executable from the same folder it resides.

### ISSUE THREAD

**Issue by MiltiadisKoutsokeras** [docker/docker.github.io#14725] opened 2022-05-12 08:08 UTC
### Problem description

The script `dockerd-rootless-setuptool.sh` is trying to invoke the `docker` executable from the same folder the script itself resides in. This problem manifests on systems that do not install the `dockerd-rootless-setuptool.sh` and `docker` executable in the same location, e.g. Debian 11 uses `/usr/share/docker.io/contrib/dockerd-rootless-setuptool.sh` and `/usr/bin/docker`. This leads to the following error when install is invoked:

```
$ dockerd-rootless-setuptool.sh install
[INFO] Creating /home/<my username>/.config/systemd/user/docker.service
[INFO] starting systemd service docker.service
+ systemctl --user start docker.service
+ sleep 3
+ systemctl --user --no-pager --full status docker.service
● docker.service - Docker Application Container Engine (Rootless)
     Loaded: loaded (/home/<my username>/.config/systemd/user/docker.service; disabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-05-12 10:27:41 EEST; 3s ago
       Docs: https://docs.docker.com/engine/security/rootless/
   Main PID: 15726 (rootlesskit)
      Tasks: 55
     Memory: 75.9M
        CPU: 195ms
     CGroup: /user.slice/user-1002.slice/user@1002.service/app.slice/docker.service
             ├─15726 rootlesskit --net=slirp4netns --mtu=65520 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=builtin --copy-up=/etc --copy-up=/run --propagation=rslave /usr/share/docker.io/contrib/dockerd-rootless.sh
             ├─15739 /proc/self/exe --net=slirp4netns --mtu=65520 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=builtin --copy-up=/etc --copy-up=/run --propagation=rslave /usr/share/docker.io/contrib/dockerd-rootless.sh
             ├─15756 slirp4netns --mtu 65520 -r 3 --disable-host-loopback --enable-sandbox --enable-seccomp 15739 tap0
             ├─15763 dockerd
             └─15791 containerd --config /run/user/1002/docker/containerd/containerd.toml --log-level info

May 12 10:27:41 <my hostname> dockerd-rootless.sh[15763]: time="2022-05-12T10:27:41.534886111+03:00" level=warning msg="Unable to find cpu controller"
May 12 10:27:41 <my hostname> dockerd-rootless.sh[15763]: time="2022-05-12T10:27:41.534894931+03:00" level=warning msg="Unable to find io controller"
May 12 10:27:41 <my hostname> dockerd-rootless.sh[15763]: time="2022-05-12T10:27:41.534898008+03:00" level=warning msg="Unable to find cpuset controller"
May 12 10:27:41 <my hostname> dockerd-rootless.sh[15763]: time="2022-05-12T10:27:41.534977755+03:00" level=info msg="Loading containers: start."
May 12 10:27:41 <my hostname> dockerd-rootless.sh[15763]: time="2022-05-12T10:27:41.536215241+03:00" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: ERROR: could not insert 'br_netfilter': Operation not permitted\ninsmod /lib/modules/5.10.0-14-amd64/kernel/net/bridge/br_netfilter.ko \n, error: exit status 1"
May 12 10:27:41 <my hostname> dockerd-rootless.sh[15763]: time="2022-05-12T10:27:41.565307766+03:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
May 12 10:27:41 <my hostname> dockerd-rootless.sh[15763]: time="2022-05-12T10:27:41.640267803+03:00" level=info msg="Loading containers: done."
May 12 10:27:41 <my hostname> dockerd-rootless.sh[15763]: time="2022-05-12T10:27:41.643238811+03:00" level=info msg="Docker daemon" commit=363e9a8 graphdriver(s)=fuse-overlayfs version=20.10.5+dfsg1
May 12 10:27:41 <my hostname> dockerd-rootless.sh[15763]: time="2022-05-12T10:27:41.643283726+03:00" level=info msg="Daemon has completed initialization"
May 12 10:27:41 <my hostname> dockerd-rootless.sh[15763]: time="2022-05-12T10:27:41.656728789+03:00" level=info msg="API listen on /run/user/1002/docker.sock"
+ DOCKER_HOST=unix:///run/user/1002/docker.sock /usr/share/docker.io/contrib/docker version
/usr/share/docker.io/contrib/dockerd-rootless-setuptool.sh: 336: /usr/share/docker.io/contrib/docker: not found
```

### Problem location

The problems lies in the script, and manifest in line 336 of current Debian 11 version installed by package `docker.io`:

```Bash
...
336:		DOCKER_HOST="unix://$XDG_RUNTIME_DIR/docker.sock" $BIN/docker version
...
```

The `BIN` variable is calculated using the location of script `dockerd-rootless.sh` which is different than the location of `docker` executable:

```Bash
...
24: DOCKERD_ROOTLESS_SH="dockerd-rootless.sh"
...
59:	if ! BIN="$(command -v "$DOCKERD_ROOTLESS_SH" 2> /dev/null)"; then
60:		ERROR "$DOCKERD_ROOTLESS_SH needs to be present under \$PATH"
61:		exit 1
62:	fi
63:	BIN=$(dirname "$BIN")\
...
```

Locations

```
/usr/share/docker.io/contrib/dockerd-rootless.sh
/usr/bin/docker
```

### Project version(s) affected

Versions:

```Text
||/ Name           Version                 Architecture Description
+++-==============-=======================-============-=================================
ii  docker.io      20.10.5+dfsg1-1+deb11u1 amd64        Linux container runtime
```

```Text
$ docker --version
Docker version 20.10.5+dfsg1, build 55c4c88
```

### Suggestions for a fix

Workaround is to place all executables using `BIN` variable for execution as symbolic links in a single folder:

```Bash
mkdir "${HOME}/.local/bin"
ln -s /usr/bin/docker "${HOME}/.local/bin/docker"
ln -s /usr/share/docker.io/contrib/dockerd-rootless-setuptool.sh "${HOME}/.local/bin/dockerd-rootless-setuptool.sh"
ln -s /usr/share/docker.io/contrib/dockerd-rootless.sh "${HOME}/.local/bin/dockerd-rootless.sh"
```

It is ugly but you do not modify any Debian package files and does not require root privilege.

A fix would calculate BIN only for executables not already in the PATH and use everything else from PATH.

**Comment by craig-osterhout** [comment] 2022-05-18 19:20
Thanks for sharing the issue and the workaround. If the issue is in the script, it's better get it fixed and document any known issues in the source repo.
I think the script is maintained at https://github.com/moby/moby/tree/master/contrib
Please help report the issue there. Closing this issue for docs, but feel free to comment to let us know more info.

**Closed by craig-osterhout** 2022-05-18 19:20 UTC

**Comment by AkihiroSuda** [comment] 2022-09-22 23:10
> Debian 11 uses /usr/share/docker.io/contrib/dockerd-rootless-setuptool.sh

Debian seems doing wrong.
Could you report the issue to Debian?
