### ISSUE TITLE
Language-specific guides request

### ISSUE THREAD

**Issue by oscarmonteiro2** [docker/docker.github.io#12451] opened 2021-03-05 22:25 UTC
### Problem description

    Where can i find  guides for c# .Net core?

### Problem location

no referencies can be found at  https://docs.docker.com/language/

**Comment by thaJeztah** [comment] 2021-12-02 14:22
Thanks for requesting; let me close this as duplicate of https://github.com/docker/docker.github.io/issues/12249 and https://github.com/docker/docker.github.io/issues/12697

**Closed by thaJeztah** 2021-12-02 14:22 UTC
