### ISSUE TITLE
maven

### ISSUE THREAD

**Issue by mazongzhu** [docker/docker.github.io#12105] opened 2021-01-15 05:44 UTC
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by sudo-bmitch** [comment] 2021-01-19 18:36
It's not clear what the issue is you are encountering. Closing for now. If you are still encountering an issue, please clarify with more details in the comments.

**Closed by sudo-bmitch** 2021-01-19 18:36 UTC
