### ISSUE TITLE
use of a folder named target is confusing with keyword target

### ISSUE THREAD

**Issue by bp100a** [docker/docker.github.io#13740] opened 2021-10-27 12:31 UTC
File: [storage/bind-mounts.md](https://docs.docker.com/storage/bind-mounts/)

In the example the usage of a folder named **target** is confusing since there's a keyword **target** that is part of the mount statement.

**Comment by craig-osterhout** [comment] 2022-05-18 21:05
Closing as duplicate of #7255

**Closed by craig-osterhout** 2022-05-18 21:05 UTC
