### ISSUE TITLE
[WIP] Update Get Started tutorial

### ISSUE THREAD

**Issue by gbarr01** [docker/docker.github.io#5807] opened 2018-01-23 19:32 UTC
- Prepare for addition of Kubernetes tutorial path (remove vizualizer, etc)
- Retest against all supported platforms
- Point to updated proxy docs
- Clean and tighten text
- Address existing GH issues regarding tutorial

**Comment by delallea** [comment] 2018-01-31 18:00
Not sure if this is the right place to post this, but since it sounds like you're modifying the example code I thought it would be worth mentioning an issue I had when doing the tutorial (under Windows 7 if that matters).

The problem is with the Python code in part 2, which connects to Redis with host="redis". But the "redis" hostname seems to only exist on the manager node, since the redis service is not deployed on the workers. Thus the example doesn't work if you connect through HTTP on the worker. I was able to fix it by specifying the manager's IP instead, but I'm not sure if there's a better way.

**Comment by gbarr01** [comment] 2018-02-23 16:48
Thanks, @delallea . I'll take a look and keep this in mind when I update the guide.

**Comment by ahh-docker** [comment] 2018-09-18 18:57
Following up with @justincormack about closing.

**Comment by L-Hudson** [comment] 2019-01-02 17:53
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Closed by L-Hudson** 2019-01-02 17:53 UTC
Labels: area/tutorials
