### ISSUE TITLE
404 at /toolbox/toolbox_install_winows

### ISSUE THREAD

**Issue by spiderH** [docker/docker.github.io#12336] opened 2021-02-16 02:16 UTC
I found a broken link : https://docs.docker.com/toolbox/toolbox_install_winows

**Comment by jerae-duffin** [comment] 2021-05-18 16:26
Hi @spiderH, thank you for sharing this issue. Can you provide more details on how you arrived to this link?

**Comment by craig-osterhout** [comment] 2022-04-26 20:36
Thanks for sharing the issue. We are unable to reproduce the issue and are closing it due to insufficient information. If you still encounter the issue, please respond with the requested details.

**Closed by craig-osterhout** 2022-04-26 20:36 UTC
