### ISSUE TITLE
Automatically import changelogs from `moby/moby`?

### ISSUE THREAD

**Issue by mstanleyjones** [docker/docker.github.io#3358] opened 2017-05-23 18:39 UTC
### Problem description

Right now we don't really expose Engine release notes in our docs. Should we figure out a way to
import the changelogs (for example https://github.com/moby/moby/releases/tag/v17.04.0-ce)? Or should we do an excerpt+rewrite strategy like I have been doing for the Edge release notes (https://docs.docker.com/edge/#docker-ce-edge-new-features)? The second way is more time-intensive but people seem to like it, and I think it adds more value.

cc/ @thaJeztah @tiborvass @vieux

**Comment by thaJeztah** [comment] 2017-05-23 22:46
@mstanleyjones I think the release notes will have to be added to the https://github.com/docker/docker-ce repository, given that moby will be the upstream, and not do releases (well, not releases that match the docker release schedule/versions)

**Comment by joaofnfernandes** [comment] 2017-08-22 18:34
I'm closing this as a duplicate of #3434.

**Closed by joaofnfernandes** 2017-08-22 18:34 UTC
