### ISSUE TITLE
Inconsistent Commands

### ISSUE THREAD

**Issue by kavikat** [docker/docker.github.io#6831] opened 2018-06-06 17:42 UTC
File: [ee/ucp/admin/install/index.md](https://docs.docker.com/ee/ucp/admin/install/)

For step 4, there is a misleading command provided:

```
# Pull the latest version of UCP
docker image pull docker/ucp:3.0.1
```

Using the ```:latest``` tag would coincide with the leading comment. Alternatively, changing the leading comment to specify a version, and changing the tag to ```:<version>``` would also provide more consistency.

**Comment by joaofnfernandes** [comment] 2018-06-08 20:08
In the past the docs told people to pull `:latest`. The problem is that if you already pulled latest in the past and still have that image in your machine, you'll be installing an older version of UCP without knowing.

I get the feedback but I think we should keep things as they are. I'm closing the issue but feel free to comment if you disagree.

**Closed by joaofnfernandes** 2018-06-08 20:08 UTC
