### ISSUE TITLE
Healthcheck change consequences

### ISSUE THREAD

**Issue by adhesivee** [docker/docker.github.io#7398] opened 2018-09-20 13:37 UTC
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

To me it is quite unclear what happens with the container when it is `starting` /  `unhealthy`. Mainly with docker-compose. For example what happens if I have 2 nodes, one of them becomes  `unhealthy`, what will happen? My assumption is it will not route to that container, but I rather see it documented.

**Comment by craig-osterhout** [comment] 2022-05-26 17:46
Thanks for sharing this issue. This particular content is maintained in an upstream repo. Since this issue is dated, I'm not sure if it is still applicable. If the issue is still applicable, please help create an issue or PR in the source repo at https://github.com/docker/cli/tree/master/docs/reference
Closing this as unable to fix in this repo.

**Closed by craig-osterhout** 2022-05-26 17:46 UTC
Labels: area/Compose
