### ISSUE TITLE
docker container ls  - Provide list of available --filters options

### ISSUE THREAD

**Issue by melbeltagy** [docker/docker.github.io#14451] opened 2022-03-25 21:06 UTC
File: [engine/reference/commandline/container_ls.md](https://docs.docker.com/engine/reference/commandline/container_ls/)

Currently, it's totally unclear which filters are supported by this command.
Trial and error and googling, led me to find out that the following options work:

- `-f name=xyz`: will filter all matching names
- `-f name=xyz*`: will filter all names that starts with `xyz`

On the other hand, the following commands are not working:
- `-f name=xyz*db`: you cannot filter names that starts and ends with specific prefix and suffix. Just results nothing without error.
- `-f image=postgres`: does not work and gives this error message: `Invalid filter 'image'`

I'm not asking for a new feature, I'm just asking to clarify what are the supported filters as part of the documentations, please.

For example, the [`search`](https://docs.docker.com/engine/reference/commandline/search/) command has a perfect `Filtering` section with example of each one.

Thank you so much

**Comment by craig-osterhout** [comment] 2022-06-01 21:15
Closing duplicate of https://github.com/docker/docker.github.io/issues/14868

**Closed by craig-osterhout** 2022-06-01 21:15 UTC
Labels: area/CLI
