### ISSUE TITLE
Feedback for: engine/reference/commandline/inspect.md

### ISSUE THREAD

**Issue by iBobik** [docker/docker.github.io#88] opened 2016-10-06 00:04 UTC
URL: engine/reference/commandline/inspect.md
and many more pages with --format examples.

Seems like template examples are missing:

$ docker inspect --format='' $INSTANCE_ID

**Comment by caseyfw** [comment] 2016-10-06 01:02
Duplicate of issue #44.

**Comment by johndmulhausen** [comment] 2016-10-07 05:02
Fixed in #48

**Closed by johndmulhausen** 2016-10-07 05:02 UTC
